#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]
#![forbid(unsafe_code)]
#![warn(clippy::pedantic)]
#![deny(clippy::unwrap_used, clippy::expect_used)]

//! `dnsqb-tray` (T-149) — a lightweight background tray icon replacing the
//! Tauri desktop window (T-52, `dnsqb-ui`, deleted alongside this crate's
//! introduction). Unlike `dnsqb-ui`, this is a genuine long-running
//! background process (SERVICES.md), started once (manually today — T-150
//! tracks real autostart, separately) and then left running: its whole job
//! is showing live resolver status in the tray tooltip and giving a
//! mouse-only user five actions without ever opening a terminal. Full
//! configuration moved to the browser (`dnsqb-service`'s own embedded
//! `/admin/ui`, T-149) — this crate has no window of its own.
//!
//! "Закрити" and "Зупинити фільтрацію" are deliberately two separate menu
//! items, not one (advisor-caught during the T-149 plan review): this tray
//! never owns `dnsqb-service` as a child process (T-150's own scoping
//! reasoning — a headless target can't depend on a graphical tray
//! supervisor to launch it), so a single "close = stop everything" action
//! would leave DNS silently unfiltered with no on-screen indication at all
//! once the tray itself is gone — the Три Б failure mode by name. "Закрити"
//! only exits this process; `dnsqb-service` keeps running. "Зупинити
//! фільтрацію" is the one action that actually calls `POST
//! /admin/shutdown`, gated behind a native confirm dialog naming that
//! consequence.
//!
//! Threading model (T-149 Крок 0, confirmed against a throwaway scratch
//! probe before writing this crate for real): `tao`'s [`EventLoop::run`]
//! hijacks the calling thread forever and is not itself `async` — so
//! polling `dnsqb-service`'s admin channel lives on a separate OS thread
//! with its own single-threaded `tokio` runtime ([`status::spawn`]),
//! publishing results the main thread reads without ever blocking on
//! network I/O itself. `muda`'s [`MenuEvent`] channel is a plain
//! lock-free queue, not wired into `tao`'s own event delivery on Windows
//! (only macOS/Linux integrate it via the native run loop, per `tray-icon`'s
//! own docs) — this loop drains it on a short fixed [`EVENT_POLL_INTERVAL`]
//! tick via `ControlFlow::WaitUntil` instead.

mod browser;
mod status;

use dnsqb_service::{
    acquire_instance_guard, app_data_dir, clear_stop_flag, ensure_sibling_running, init_logging,
    set_quit_flag, set_stop_flag, stop_flag_is_set, write_pid_file, AdminClient, AdminClientError,
    GuardError, InstanceRole, ResolverConfig,
};
use dnsqb_service::{
    ensure_installed, remove_all_local_state, rotate_certificate,
    uninstall as uninstall_trust_store, ArtifactOutcome, UninstallReport,
};
use status::TrayStatus;
use std::path::{Path, PathBuf};
use std::time::{Duration, Instant};
use tao::event_loop::{ControlFlow, EventLoop};
use tray_icon::menu::{Menu, MenuEvent, MenuItem, PredefinedMenuItem};
use tray_icon::{Icon, TrayIconBuilder};

// Raw 32x32 RGBA pixels (4096 bytes, no header), transparent background +
// white hexagon glyph — `tray_icon::Icon::from_rgba` takes raw pixels, not an
// encoded image, so compiling the blob in avoids both a runtime filesystem
// read and an image-decode dependency (the same "everything in, no runtime
// asset I/O" choice `admin_ui.rs` makes for the embedded web UI).
// Generated by `assets/gen-icon.py` (`make_tray_glyph`), the single source
// for every project icon — re-run that script to regenerate, never hand-edit
// the .bin (T-183; the previous blob was a stale copy of the deleted
// `dnsqb-ui`'s Tauri icon and rendered as a plain teal square).
const ICON_RGBA: &[u8] = include_bytes!("../icons/tray-32-rgba.bin");
const ICON_SIZE: u32 = 32;

const OPEN_SETTINGS_ID: &str = "open-settings";
const RESTART_ID: &str = "restart";
const ABOUT_ID: &str = "about";
const PAUSE_RESUME_ID: &str = "pause-resume-filtering";
const RESTORE_SUPERVISION_ID: &str = "restore-supervision";
const QUIT_APP_ID: &str = "quit-app";
const CLOSE_ID: &str = "close";
const INSTALL_CERT_ID: &str = "install-cert";
const UNINSTALL_CERT_ID: &str = "uninstall-cert";
const ROTATE_CERT_ID: &str = "rotate-cert";
const REMOVE_ALL_ID: &str = "remove-all-local-state";

const PAUSE_LABEL: &str = "Призупинити фільтрацію";
const RESUME_LABEL: &str = "Відновити фільтрацію";

/// Re-check cadence for `muda`'s global menu-event channel (see the module
/// doc comment for why this loop drives it rather than `tao` itself) —
/// independent of [`status::spawn`]'s own 2s poll interval; this tick only
/// governs how quickly a menu click gets noticed.
const EVENT_POLL_INTERVAL: Duration = Duration::from_millis(100);

/// How often the event loop re-stats `stop.flag` to keep the pause/resume
/// label current (T-185). The flag only changes on a click handled here or a
/// fresh watcher launch clearing it, so statting it on every 100 ms
/// [`EVENT_POLL_INTERVAL`] tick is far more often than needed (advisor,
/// Батч 3.12 closing).
const FLAG_CHECK_INTERVAL: Duration = Duration::from_secs(1);

fn main() {
    let app_data = match app_data_dir() {
        Ok(dir) => {
            init_logging("dnsqb-tray", Some(&dir)); // T-184
            dir
        }
        Err(err) => {
            init_logging("dnsqb-tray", None);
            tracing::error!("no app-data directory available, dnsqb-tray cannot run: {err}");
            std::process::exit(1);
        }
    };

    // SPEC.md §7.1 #2/#3: one tray per app-data directory, and a `tray.pid`
    // the watcher's launcher reads to decide whether to spawn one (T-150) —
    // without it, every watcher (re)start would spawn another tray. A second
    // instance (a double-clicked shortcut, the watcher relaunching) just
    // exits; that is the idempotent-launcher behaviour, not an error. `tao`'s
    // event loop never returns, so the guard is released by the OS on exit
    // (its whole `share_mode(0)` design) rather than by `Drop`.
    let _guard = match acquire_instance_guard(&app_data, InstanceRole::Tray) {
        Ok(guard) => guard,
        Err(GuardError::AlreadyRunning(_)) => {
            tracing::info!("another dnsqb-tray instance is already running, exiting");
            return;
        }
        Err(err) => {
            tracing::error!("could not acquire the tray single-instance lock: {err}");
            std::process::exit(1);
        }
    };
    if let Err(err) = write_pid_file(&app_data, InstanceRole::Tray) {
        tracing::warn!("could not write the tray pid file: {err}");
    }

    // T-187 safety net: normally the watcher spawns this tray, so a watcher is
    // already up. But if `dnsqb-tray.exe` was launched on its own (a stray
    // double-click of the wrong file), bring the watcher up so the user isn't
    // left with an unsupervised or absent service. Not an inversion of the
    // hierarchy — the watcher stays the root; this is idempotent and a no-op
    // when a watcher is already running.
    ensure_sibling_running(&app_data, InstanceRole::Watcher);

    let port = match ResolverConfig::load(&app_data.join("resolver_config.toml")) {
        Ok(config) => config.port,
        Err(err) => {
            tracing::error!("failed to load resolver_config.toml: {err}");
            std::process::exit(1);
        }
    };

    let status_handle = status::spawn(app_data.clone(), port);

    let Ok(icon) = Icon::from_rgba(ICON_RGBA.to_vec(), ICON_SIZE, ICON_SIZE) else {
        tracing::error!(
            "embedded tray icon failed to decode - this is a build-time asset, not user input"
        );
        std::process::exit(1);
    };
    let (menu, pause_resume_item) = build_menu(&app_data);
    let tray_icon = match TrayIconBuilder::new()
        .with_menu(Box::new(menu))
        .with_icon(icon)
        .with_tooltip(TrayStatus::Unreachable.tooltip())
        .build()
    {
        Ok(tray_icon) => tray_icon,
        Err(err) => {
            tracing::error!("failed to create the tray icon: {err}");
            std::process::exit(1);
        }
    };

    let menu_channel = MenuEvent::receiver();
    let mut last_status = TrayStatus::Unreachable;
    let mut last_paused = stop_flag_is_set(&app_data);
    let mut last_flag_check = Instant::now();

    let event_loop: EventLoop<()> = EventLoop::new();
    event_loop.run(move |_event, _target, control_flow| {
        *control_flow = ControlFlow::WaitUntil(Instant::now() + EVENT_POLL_INTERVAL);

        let observed = status_handle.current();
        if observed != last_status {
            if let Err(err) = tray_icon.set_tooltip(Some(observed.tooltip())) {
                tracing::warn!("failed to update tray tooltip: {err}");
            }
            last_status = observed;
        }

        // T-185: flip the pause/resume label when `stop.flag` appears or is
        // removed (by this menu, or by a fresh watcher launch clearing it) —
        // re-stat it at most once a second, not on every 100 ms tick.
        if last_flag_check.elapsed() >= FLAG_CHECK_INTERVAL {
            last_flag_check = Instant::now();
            let paused = stop_flag_is_set(&app_data);
            if paused != last_paused {
                pause_resume_item.set_text(if paused { RESUME_LABEL } else { PAUSE_LABEL });
                last_paused = paused;
            }
        }

        if let Ok(event) = menu_channel.try_recv() {
            handle_menu_event(event.id().as_ref(), &app_data, port, control_flow);
        }
    });
}

/// Builds the tray menu and returns it together with a handle to the
/// pause/resume item, whose label the event loop flips between
/// [`PAUSE_LABEL`] and [`RESUME_LABEL`] as `stop.flag` comes and goes (T-185).
fn build_menu(app_data: &Path) -> (Menu, MenuItem) {
    let menu = Menu::new();
    let open_settings = MenuItem::with_id(OPEN_SETTINGS_ID, "Відкрити налаштування", true, None);
    let restart = MenuItem::with_id(RESTART_ID, "Скинути кеш і лог", true, None);
    let about = MenuItem::with_id(ABOUT_ID, "Про програму", true, None);
    let install_cert = MenuItem::with_id(INSTALL_CERT_ID, "Встановити сертифікат", true, None);
    let uninstall_cert = MenuItem::with_id(UNINSTALL_CERT_ID, "Видалити сертифікат", true, None);
    let rotate_cert = MenuItem::with_id(ROTATE_CERT_ID, "Перевипустити сертифікат", true, None);
    let remove_all = MenuItem::with_id(REMOVE_ALL_ID, "Повністю видалити", true, None);

    // Lifecycle group (Варіант B): pause/resume · restore supervision · [sep]
    // · hide icon · quit.
    let pause_resume_label = if stop_flag_is_set(app_data) {
        RESUME_LABEL
    } else {
        PAUSE_LABEL
    };
    let pause_resume = MenuItem::with_id(PAUSE_RESUME_ID, pause_resume_label, true, None);
    let restore_supervision =
        MenuItem::with_id(RESTORE_SUPERVISION_ID, "Відновити нагляд", true, None);
    let hide_icon = MenuItem::with_id(CLOSE_ID, "Сховати іконку", true, None);
    let quit_app = MenuItem::with_id(QUIT_APP_ID, "Вийти з DNS Quorum Filter", true, None);

    if let Err(err) = menu.append_items(&[
        &open_settings,
        &restart,
        &about,
        &PredefinedMenuItem::separator(),
        &install_cert,
        &uninstall_cert,
        &rotate_cert,
        &PredefinedMenuItem::separator(),
        &remove_all,
        &PredefinedMenuItem::separator(),
        &pause_resume,
        &restore_supervision,
        &PredefinedMenuItem::separator(),
        &hide_icon,
        &quit_app,
    ]) {
        tracing::warn!("failed to build the full tray menu: {err}");
    }
    (menu, pause_resume)
}

fn handle_menu_event(id: &str, app_data: &Path, port: u16, control_flow: &mut ControlFlow) {
    match id {
        OPEN_SETTINGS_ID => {
            browser::open_in_default_browser(&format!("https://127.0.0.1:{port}/admin/ui"));
        }
        RESTART_ID => {
            spawn_admin_action(app_data.to_path_buf(), port, "reset", |client| async move {
                client.reset().await.map(|_response| ())
            });
        }
        ABOUT_ID => show_about_dialog(),
        INSTALL_CERT_ID => {
            if confirm_install_cert() {
                let cert_path = app_data.join("cert.pem");
                spawn_trust_store_action(
                    "install",
                    "Встановити сертифікат",
                    move || ensure_installed(&cert_path).map(|outcome| format!("{outcome:?}")),
                );
            }
        }
        UNINSTALL_CERT_ID => {
            if confirm_uninstall_cert() {
                spawn_trust_store_action(
                    "uninstall",
                    "Видалити сертифікат",
                    || uninstall_trust_store().map(|()| "removed".to_string()),
                );
            }
        }
        ROTATE_CERT_ID => {
            if confirm_rotate_cert() {
                spawn_trust_store_action(
                    "rotate",
                    "Перевипустити сертифікат",
                    || rotate_certificate().map(|report| report.to_string()),
                );
            }
        }
        REMOVE_ALL_ID => {
            if confirm_remove_all_local_state() {
                let app_data = app_data.to_path_buf();
                spawn_trust_store_action(
                    "remove-all-local-state",
                    "Повністю видалити",
                    move || -> Result<String, std::convert::Infallible> {
                        Ok(format_uninstall_report(&remove_all_local_state(Some(
                            &app_data,
                        ))))
                    },
                );
            }
        }
        // T-185: pause = write `stop.flag` (so the watchdog won't respawn),
        // then ask the service to shut down. Resume = remove the flag and
        // relaunch the service. The label the user clicked tells us which.
        PAUSE_RESUME_ID => {
            if stop_flag_is_set(app_data) {
                clear_stop_flag(app_data);
                ensure_sibling_running(app_data, InstanceRole::Service);
                tracing::info!("filtering resumed by the user");
            } else if confirm_pause() {
                if let Err(err) = set_stop_flag(app_data) {
                    tracing::warn!("could not write stop.flag: {err}");
                }
                spawn_admin_action(
                    app_data.to_path_buf(),
                    port,
                    "shutdown",
                    |client| async move { client.shutdown().await },
                );
            }
        }
        // T-185: bring the watchdog back if it stopped (idempotent — a no-op
        // when a watcher is already running). This is the only actionable
        // recovery for a dead watcher; there is no automatic one yet.
        RESTORE_SUPERVISION_ID => {
            ensure_sibling_running(app_data, InstanceRole::Watcher);
        }
        // T-185: quit the whole app. Write both flags and exit the tray; the
        // watcher picks up `quit.flag` on its next tick, stops the service and
        // exits itself. `stop.flag` covers the gap so nothing is respawned in
        // between.
        QUIT_APP_ID => {
            if confirm_quit() {
                if let Err(err) = set_stop_flag(app_data) {
                    tracing::warn!("could not write stop.flag: {err}");
                }
                if let Err(err) = set_quit_flag(app_data) {
                    tracing::warn!("could not write quit.flag: {err}");
                }
                *control_flow = ControlFlow::Exit;
            }
        }
        // "Сховати іконку" only exits this process — dnsqb-service and the
        // watcher keep running, filtering stays on. "Вийти з DNS Quorum
        // Filter" above is the one that stops everything.
        CLOSE_ID => *control_flow = ControlFlow::Exit,
        _ => {}
    }
}

/// Runs one admin-channel action (`reset`/`shutdown`) on its own throwaway
/// OS thread with its own tiny runtime — these are rare, user-initiated
/// clicks, not a hot path, so building a fresh [`AdminClient`] per call is
/// fine here (same cadence the old `dnsqb-ui` Tauri commands already used) —
/// unlike [`status::spawn`]'s ~30x/minute poll, which specifically must not
/// rebuild one every tick.
fn spawn_admin_action<F, Fut>(app_data: PathBuf, port: u16, action_name: &'static str, action: F)
where
    F: FnOnce(AdminClient) -> Fut + Send + 'static,
    Fut: std::future::Future<Output = Result<(), AdminClientError>>,
{
    std::thread::spawn(move || {
        let Ok(runtime) = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
        else {
            tracing::error!("failed to start a runtime for the {action_name} action");
            return;
        };
        runtime.block_on(async move {
            match AdminClient::new(&app_data, port) {
                Ok(client) => match action(client).await {
                    Ok(()) => tracing::info!("{action_name} succeeded"),
                    Err(err) => tracing::warn!("{action_name} failed: {err}"),
                },
                Err(err) => {
                    tracing::warn!("{action_name} failed to build an admin client: {err}");
                }
            }
        });
    });
}

/// Runs one trust-store action (`install`/`uninstall`) on its own throwaway
/// OS thread — unlike [`spawn_admin_action`], this is a synchronous local
/// `certutil` call, not an admin-HTTP-channel round trip, so no `tokio`
/// runtime is needed at all. Reports the outcome **both** ways: logged (as
/// every other action here does) and via a native dialog on this same
/// thread — this crate builds with `windows_subsystem = "windows"` (no
/// console), so a log line alone is invisible to a user who clicked a menu
/// item and is watching for a result. A silent failure here would leave the
/// user believing a trust-store change succeeded when it didn't — exactly
/// the "no on-screen indication" failure class this crate's own module doc
/// comment already names for "Зупинити фільтрацію" (advisor-caught before
/// commit, not written this way from the start).
fn spawn_trust_store_action<F, E>(action_name: &'static str, dialog_title: &'static str, action: F)
where
    F: FnOnce() -> Result<String, E> + Send + 'static,
    E: std::fmt::Display,
{
    std::thread::spawn(move || match action() {
        Ok(outcome) => {
            tracing::info!("{action_name} succeeded: {outcome}");
            rfd::MessageDialog::new()
                .set_title(dialog_title)
                .set_description(format!("Успішно: {outcome}"))
                .set_level(rfd::MessageLevel::Info)
                .set_buttons(rfd::MessageButtons::Ok)
                .show();
        }
        Err(err) => {
            tracing::warn!("{action_name} failed: {err}");
            rfd::MessageDialog::new()
                .set_title(dialog_title)
                .set_description(format!("Не вдалося: {err}"))
                .set_level(rfd::MessageLevel::Error)
                .set_buttons(rfd::MessageButtons::Ok)
                .show();
        }
    });
}

/// Native confirm dialog before `certutil -addstore` — this pops the OS's
/// own confirmation dialog too (a second, separate prompt) unless/until
/// T-49's open "is certutil silent?" question is settled by a real run; see
/// `trust_store.rs`'s module doc comment.
fn confirm_install_cert() -> bool {
    let result = rfd::MessageDialog::new()
        .set_title("Встановити сертифікат")
        .set_description(
            "Локальний сертифікат dns-quorum-filter буде додано до довірених кореневих \
             сертифікатів поточного користувача (CurrentUser\\Root). Це прибирає попередження \
             браузера про недовірений сертифікат на сторінці налаштувань. Windows може показати \
             власний діалог підтвердження. Продовжити?",
        )
        .set_level(rfd::MessageLevel::Info)
        .set_buttons(rfd::MessageButtons::YesNo)
        .show();
    result == rfd::MessageDialogResult::Yes
}

/// Native confirm dialog before `certutil -delstore` — names the real
/// consequence (browser warning returns), same pattern as [`confirm_pause`].
fn confirm_uninstall_cert() -> bool {
    let result = rfd::MessageDialog::new()
        .set_title("Видалити сертифікат")
        .set_description(
            "Локальний сертифікат dns-quorum-filter буде видалено з довірених кореневих \
             сертифікатів. Браузер знову покаже попередження про недовірений сертифікат на \
             сторінці налаштувань, доки сертифікат не буде встановлено повторно. Продовжити?",
        )
        .set_level(rfd::MessageLevel::Warning)
        .set_buttons(rfd::MessageButtons::YesNo)
        .show();
    result == rfd::MessageDialogResult::Yes
}

/// Native confirm dialog before certificate rotation — names every consequence
/// *before* the user acts: the old `CurrentUser\Root` entries are removed, a
/// fresh key is generated and the new certificate installed in their place, and
/// the running `dnsqb-service` keeps serving the *previous* certificate (it
/// holds its TLS config from startup) until it is restarted. In that window the
/// browser shows an untrusted-certificate warning on `/admin/ui` because the
/// certificate on the wire is no longer in the trust store; restarting
/// `dnsqb-service` clears it. (The tray's own status poll is unaffected —
/// [`status::spawn`] keeps its cached client, still pinned to and matching the
/// still-served previous certificate.)
fn confirm_rotate_cert() -> bool {
    let result = rfd::MessageDialog::new()
        .set_title("Перевипустити сертифікат")
        .set_description(
            "Буде згенеровано новий локальний сертифікат dns-quorum-filter із новим ключем. \
             Старі записи цього проєкту прибираються з довірених кореневих сертифікатів \
             (CurrentUser\\Root), новий сертифікат встановлюється замість них. \
             dnsqb-service потрібно перезапустити, щоб новий сертифікат почав діяти — до \
             перезапуску сервіс віддає попередній сертифікат, і браузер показуватиме \
             попередження про недовірений сертифікат на сторінці налаштувань. Після \
             перезапуску воно зникає. Продовжити?",
        )
        .set_level(rfd::MessageLevel::Warning)
        .set_buttons(rfd::MessageButtons::YesNo)
        .show();
    result == rfd::MessageDialogResult::Yes
}

/// Native confirm dialog before T-70's full local-state removal — names
/// every artifact it touches (the trusted certificate *and* all three
/// Credential Manager secrets) and the one thing it deliberately does
/// **not** do: MSIX (T-156) gives this app no code to run at uninstall
/// time, so removing the app itself is still a separate, manual step in
/// Windows Settings.
fn confirm_remove_all_local_state() -> bool {
    let result = rfd::MessageDialog::new()
        .set_title("Повністю видалити")
        .set_description(
            "Буде видалено локальний сертифікат dns-quorum-filter із довірених кореневих \
             сертифікатів, а також TLS-ключ, ключ шифрування журналу/кешу та збережені \
             креденшели MaxMind (якщо є) зі сховища облікових даних Windows. Це НЕ видаляє \
             сам застосунок — після цього кроку видаліть dns-quorum-filter у Параметрах \
             Windows окремо. Продовжити?",
        )
        .set_level(rfd::MessageLevel::Warning)
        .set_buttons(rfd::MessageButtons::YesNo)
        .show();
    result == rfd::MessageDialogResult::Yes
}

/// One line per artifact, never a single collapsed pass/fail — the same
/// discipline [`UninstallReport`] itself follows.
fn format_uninstall_report(report: &UninstallReport) -> String {
    fn line(label: &str, outcome: ArtifactOutcome) -> String {
        let text = match outcome {
            ArtifactOutcome::Removed => "видалено",
            ArtifactOutcome::NotPresent => "не було встановлено",
            ArtifactOutcome::Failed(_) => "НЕ ВДАЛОСЯ видалити",
        };
        format!("{label}: {text}")
    }
    [
        line("Сертифікат", report.cert),
        line("TLS-ключ", report.tls_key),
        line("Ключ шифрування", report.persistence_key),
        line("Креденшели MaxMind", report.maxmind_creds),
    ]
    .join("\n")
}

fn show_about_dialog() {
    rfd::MessageDialog::new()
        .set_title("dns-quorum-filter")
        .set_description(format!(
            "dnsqb-tray {}\nЛіцензія: Apache-2.0\nЛокальний DoH quorum-фільтр \u{2014} \
             https://127.0.0.1/admin/ui",
            env!("CARGO_PKG_VERSION")
        ))
        .set_level(rfd::MessageLevel::Info)
        .set_buttons(rfd::MessageButtons::Ok)
        .show();
}

/// Native confirm dialog before pausing filtering (T-185). Names the
/// consequence and every way to undo it — unlike the old "Зупинити
/// фільтрацію", this state is reversible from the same menu, and a fresh app
/// launch also clears `stop.flag`, so the dialog must say so (advisor,
/// Батч 3.12 closing — the earlier wording promised the pause held until an
/// explicit resume, which is false across a restart).
fn confirm_pause() -> bool {
    let result = rfd::MessageDialog::new()
        .set_title("Призупинити фільтрацію")
        .set_description(
            "DNS піде нефільтрованим. Щоб відновити фільтрацію — натисніть «Відновити \
             фільтрацію» в цьому ж меню або перезапустіть застосунок. Продовжити?",
        )
        .set_level(rfd::MessageLevel::Warning)
        .set_buttons(rfd::MessageButtons::YesNo)
        .show();
    result == rfd::MessageDialogResult::Yes
}

/// Native confirm dialog before quitting the whole app (T-185) — this stops
/// the service, the watchdog and the tray. Same blast-radius warning shape as
/// [`confirm_pause`], stronger wording.
fn confirm_quit() -> bool {
    let result = rfd::MessageDialog::new()
        .set_title("Вийти з DNS Quorum Filter")
        .set_description(
            "Застосунок повністю зупиниться: DNS-фільтрація, фоновий нагляд і ця іконка. \
             DNS піде нефільтрованим, доки ви знову не запустите застосунок із меню Пуск. \
             Продовжити?",
        )
        .set_level(rfd::MessageLevel::Warning)
        .set_buttons(rfd::MessageButtons::YesNo)
        .show();
    result == rfd::MessageDialogResult::Yes
}
