#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]
#![forbid(unsafe_code)]
#![warn(clippy::pedantic)]
#![deny(clippy::unwrap_used, clippy::expect_used)]

//! `dnsqb-tray` (T-149) — a lightweight background tray icon replacing the
//! Tauri desktop window (T-52, `dnsqb-ui`, deleted alongside this crate's
//! introduction). Unlike `dnsqb-ui`, this is a genuine long-running
//! background process (SERVICES.md), started once (manually today — T-150
//! tracks real autostart, separately) and then left running: its whole job
//! is showing live resolver status in the tray tooltip and giving a
//! mouse-only user five actions without ever opening a terminal. Full
//! configuration moved to the browser (`dnsqb-service`'s own embedded
//! `/admin/ui`, T-149) — this crate has no window of its own.
//!
//! "Закрити" and "Зупинити фільтрацію" are deliberately two separate menu
//! items, not one (advisor-caught during the T-149 plan review): this tray
//! never owns `dnsqb-service` as a child process (T-150's own scoping
//! reasoning — a headless target can't depend on a graphical tray
//! supervisor to launch it), so a single "close = stop everything" action
//! would leave DNS silently unfiltered with no on-screen indication at all
//! once the tray itself is gone — the Три Б failure mode by name. "Закрити"
//! only exits this process; `dnsqb-service` keeps running. "Зупинити
//! фільтрацію" is the one action that actually calls `POST
//! /admin/shutdown`, gated behind a native confirm dialog naming that
//! consequence.
//!
//! Threading model (T-149 Крок 0, confirmed against a throwaway scratch
//! probe before writing this crate for real): `tao`'s [`EventLoop::run`]
//! hijacks the calling thread forever and is not itself `async` — so
//! polling `dnsqb-service`'s admin channel lives on a separate OS thread
//! with its own single-threaded `tokio` runtime ([`status::spawn`]),
//! publishing results the main thread reads without ever blocking on
//! network I/O itself. `muda`'s [`MenuEvent`] channel is a plain
//! lock-free queue, not wired into `tao`'s own event delivery on Windows
//! (only macOS/Linux integrate it via the native run loop, per `tray-icon`'s
//! own docs) — this loop drains it on a short fixed [`EVENT_POLL_INTERVAL`]
//! tick via `ControlFlow::WaitUntil` instead.

mod browser;
mod browser_nudge;
mod onboarding;
mod self_uninstall;
mod status;

use dnsqb_service::{
    acquire_instance_guard, app_data_dir, clear_stop_flag, ensure_sibling_running, init_logging,
    set_quit_flag, set_stop_flag, stop_flag_is_set, write_pid_file, AdminClient, AdminClientError,
    GuardError, InstanceRole, ResolverConfig,
};
use dnsqb_service::{
    ensure_installed, remove_all_local_state, rotate_certificate,
    uninstall as uninstall_trust_store, ArtifactOutcome, UninstallReport,
};
use status::{IconColour, TrayStatus, TrustState};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::{Duration, Instant, SystemTime};
use tao::event_loop::{ControlFlow, EventLoop};
use tray_icon::menu::{Menu, MenuEvent, MenuItem, PredefinedMenuItem};
use tray_icon::{Icon, TrayIcon, TrayIconBuilder};

// Four raw 32x32 RGBA blobs (4096 bytes each, no header), transparent
// background + a hexagon glyph in the per-status colour (green / amber / grey
// / red) — `tray_icon::Icon::from_rgba` takes raw pixels, not an encoded
// image, so compiling the blobs in avoids both a runtime filesystem read and
// an image-decode dependency (the same "everything in, no runtime asset I/O"
// choice `admin_ui.rs` makes for the embedded web UI). Generated by
// `assets/gen-icon.py` (`make_tray_glyph(size, colour)`), the single source
// for every project icon — re-run that script to regenerate, never hand-edit
// a .bin (T-191, extending T-183's single white glyph). `status::icon_colour`
// picks which one from the live `TrayStatus` + cert-trust state.
const ICON_GREEN: &[u8] = include_bytes!("../icons/tray-32-green-rgba.bin");
const ICON_AMBER: &[u8] = include_bytes!("../icons/tray-32-amber-rgba.bin");
const ICON_GREY: &[u8] = include_bytes!("../icons/tray-32-grey-rgba.bin");
const ICON_RED: &[u8] = include_bytes!("../icons/tray-32-red-rgba.bin");
const ICON_SIZE: u32 = 32;

/// The four decoded status icons, built once at startup. `tray_icon::Icon` is
/// `Clone`, so [`Self::get`] hands `set_icon` an owned copy per update.
struct TrayIcons {
    green: Icon,
    amber: Icon,
    grey: Icon,
    red: Icon,
}

impl TrayIcons {
    /// Decodes all four build-time blobs. `None` on any failure — a build-time
    /// asset that won't decode is fatal, the same handling the pre-T-191
    /// single-icon path had.
    fn build() -> Option<Self> {
        let decode = |bytes: &[u8]| Icon::from_rgba(bytes.to_vec(), ICON_SIZE, ICON_SIZE).ok();
        Some(Self {
            green: decode(ICON_GREEN)?,
            amber: decode(ICON_AMBER)?,
            grey: decode(ICON_GREY)?,
            red: decode(ICON_RED)?,
        })
    }

    fn get(&self, colour: IconColour) -> Icon {
        match colour {
            IconColour::Green => self.green.clone(),
            IconColour::Amber => self.amber.clone(),
            IconColour::Grey => self.grey.clone(),
            IconColour::Red => self.red.clone(),
        }
    }
}

const OPEN_SETTINGS_ID: &str = "open-settings";
const RESTART_ID: &str = "restart";
const ABOUT_ID: &str = "about";
const PAUSE_RESUME_ID: &str = "pause-resume-filtering";
const RESTORE_SUPERVISION_ID: &str = "restore-supervision";
const QUIT_APP_ID: &str = "quit-app";
const CLOSE_ID: &str = "close";
const SETUP_WIZARD_ID: &str = "setup-wizard";
const INSTALL_CERT_ID: &str = "install-cert";
const UNINSTALL_CERT_ID: &str = "uninstall-cert";
const ROTATE_CERT_ID: &str = "rotate-cert";
const REMOVE_ALL_ID: &str = "remove-all-local-state";

const PAUSE_LABEL: &str = "Призупинити фільтрацію";
const RESUME_LABEL: &str = "Відновити фільтрацію";

/// Re-check cadence for `muda`'s global menu-event channel (see the module
/// doc comment for why this loop drives it rather than `tao` itself) —
/// independent of [`status::spawn`]'s own 2s poll interval; this tick only
/// governs how quickly a menu click gets noticed.
const EVENT_POLL_INTERVAL: Duration = Duration::from_millis(100);

/// How often the event loop re-stats `stop.flag` to keep the pause/resume
/// label current (T-185). The flag only changes on a click handled here or a
/// fresh watcher launch clearing it, so statting it on every 100 ms
/// [`EVENT_POLL_INTERVAL`] tick is far more often than needed (advisor,
/// Батч 3.12 closing).
const FLAG_CHECK_INTERVAL: Duration = Duration::from_secs(1);

fn main() {
    let app_data = match app_data_dir() {
        Ok(dir) => {
            init_logging("dnsqb-tray", Some(&dir)); // T-184
            dir
        }
        Err(err) => {
            init_logging("dnsqb-tray", None);
            tracing::error!("no app-data directory available, dnsqb-tray cannot run: {err}");
            std::process::exit(1);
        }
    };

    // SPEC.md §7.1 #2/#3: one tray per app-data directory, and a `tray.pid`
    // the watcher's launcher reads to decide whether to spawn one (T-150) —
    // without it, every watcher (re)start would spawn another tray. A second
    // instance (a double-clicked shortcut, the watcher relaunching) just
    // exits; that is the idempotent-launcher behaviour, not an error. `tao`'s
    // event loop never returns, so the guard is released by the OS on exit
    // (its whole `share_mode(0)` design) rather than by `Drop`.
    let _guard = match acquire_instance_guard(&app_data, InstanceRole::Tray) {
        Ok(guard) => guard,
        Err(GuardError::AlreadyRunning(_)) => {
            tracing::info!("another dnsqb-tray instance is already running, exiting");
            return;
        }
        Err(err) => {
            tracing::error!("could not acquire the tray single-instance lock: {err}");
            std::process::exit(1);
        }
    };
    if let Err(err) = write_pid_file(&app_data, InstanceRole::Tray) {
        tracing::warn!("could not write the tray pid file: {err}");
    }

    // T-187 safety net: normally the watcher spawns this tray, so a watcher is
    // already up. But if `dnsqb-tray.exe` was launched on its own (a stray
    // double-click of the wrong file), bring the watcher up so the user isn't
    // left with an unsupervised or absent service. Not an inversion of the
    // hierarchy — the watcher stays the root; this is idempotent and a no-op
    // when a watcher is already running.
    ensure_sibling_running(&app_data, InstanceRole::Watcher);

    let port = match ResolverConfig::load(&app_data.join("resolver_config.toml")) {
        Ok(config) => config.port,
        Err(err) => {
            tracing::error!("failed to load resolver_config.toml: {err}");
            std::process::exit(1);
        }
    };

    // T-229: the earliest-launch stamp for the browser-nudge threshold below
    // must be written unconditionally at every startup (idempotent — only the
    // first call ever actually creates the file), not lazily on first poll
    // tick, so a tray that never reaches a later tick still has it recorded.
    browser_nudge::mark_first_seen_if_absent(&app_data, SystemTime::now());

    let status_handle = status::spawn(app_data.clone(), port);
    let trust = status::spawn_trust_watch(app_data.join("cert.pem"));

    let Some(icons) = TrayIcons::build() else {
        tracing::error!(
            "an embedded tray icon failed to decode - these are build-time assets, not user input"
        );
        std::process::exit(1);
    };
    let (menu, pause_resume_item) = build_menu(&app_data);
    // Start on red, matching the initial `TrayStatus::Unreachable` tooltip
    // below — icon and tooltip agree from the first frame.
    let tray_icon = match TrayIconBuilder::new()
        .with_menu(Box::new(menu))
        .with_icon(icons.get(IconColour::Red))
        .with_tooltip(TrayStatus::Unreachable.tooltip())
        .build()
    {
        Ok(tray_icon) => tray_icon,
        Err(err) => {
            tracing::error!("failed to create the tray icon: {err}");
            std::process::exit(1);
        }
    };

    let menu_channel = MenuEvent::receiver();
    let mut last_status = TrayStatus::Unreachable;
    let mut last_trusted = trust.is_trusted();
    let mut last_colour = IconColour::Red;
    let mut last_paused = stop_flag_is_set(&app_data);
    let mut last_flag_check = Instant::now();
    let mut onboarding_offered = false;
    let mut browser_nudge_offered = false;

    let event_loop: EventLoop<()> = EventLoop::new();
    event_loop.run(move |_event, _target, control_flow| {
        *control_flow = ControlFlow::WaitUntil(Instant::now() + EVENT_POLL_INTERVAL);

        // T-195: the "Повністю видалити" worker sets this once the report
        // dialog is dismissed and the wipe helper is spawned. Checked after
        // the `WaitUntil` assignment above so it isn't overwritten; the
        // `return` drops this tick's queued menu event, which is fine here
        // (do not copy this pattern to the pause/label path).
        if QUIT_REQUESTED.load(Ordering::SeqCst) {
            *control_flow = ControlFlow::Exit;
            return;
        }

        let observed = status_handle.current();
        let trusted = trust.is_trusted();
        refresh_tray(
            &tray_icon,
            &icons,
            observed,
            trusted,
            &mut last_status,
            &mut last_trusted,
            &mut last_colour,
        );
        maybe_offer_onboarding(&mut onboarding_offered, &app_data, port, &trust, trusted);
        maybe_offer_browser_nudge(&mut browser_nudge_offered, &app_data, observed);

        // T-185: flip the pause/resume label when `stop.flag` appears or is
        // removed (by this menu, or by a fresh watcher launch clearing it) —
        // re-stat it at most once a second, not on every 100 ms tick.
        if last_flag_check.elapsed() >= FLAG_CHECK_INTERVAL {
            last_flag_check = Instant::now();
            let paused = stop_flag_is_set(&app_data);
            if paused != last_paused {
                pause_resume_item.set_text(if paused { RESUME_LABEL } else { PAUSE_LABEL });
                last_paused = paused;
            }
        }

        if let Ok(event) = menu_channel.try_recv() {
            handle_menu_event(event.id().as_ref(), &app_data, port, control_flow, &trust);
        }
    });
}

/// Tooltip + icon refresh on one event-loop tick (T-191). The tooltip is
/// driven by `(observed, trusted)` — not `observed` alone — so that clicking
/// "Встановити сертифікат" while filtering, which flips only `trusted`, still
/// re-renders it (the cert-warning suffix, [`status::compose_tooltip`]). A
/// failed `set_tooltip` is cosmetic and self-heals on the next change, so
/// `last_status`/`last_trusted` commit unconditionally; `last_colour` commits
/// **only on `set_icon` success**, or one transient failure would make the
/// `colour != *last_colour` guard read equal forever and pin the wrong colour.
fn refresh_tray(
    tray_icon: &TrayIcon,
    icons: &TrayIcons,
    observed: TrayStatus,
    trusted: bool,
    last_status: &mut TrayStatus,
    last_trusted: &mut bool,
    last_colour: &mut IconColour,
) {
    if observed != *last_status || trusted != *last_trusted {
        let tooltip = status::compose_tooltip(observed, trusted);
        if let Err(err) = tray_icon.set_tooltip(Some(tooltip)) {
            tracing::warn!("failed to update tray tooltip: {err}");
        }
        *last_status = observed;
        *last_trusted = trusted;
    }

    let colour = status::icon_colour(observed, trusted);
    if colour != *last_colour {
        match tray_icon.set_icon(Some(icons.get(colour))) {
            Ok(()) => *last_colour = colour,
            Err(err) => tracing::warn!("failed to update tray icon colour: {err}"),
        }
    }
}

/// Builds the tray menu and returns it together with a handle to the
/// pause/resume item, whose label the event loop flips between
/// [`PAUSE_LABEL`] and [`RESUME_LABEL`] as `stop.flag` comes and goes (T-185).
fn build_menu(app_data: &Path) -> (Menu, MenuItem) {
    let menu = Menu::new();
    let open_settings = MenuItem::with_id(OPEN_SETTINGS_ID, "Відкрити налаштування", true, None);
    let restart = MenuItem::with_id(RESTART_ID, "Скинути кеш і лог", true, None);
    let about = MenuItem::with_id(ABOUT_ID, "Про програму", true, None);
    let setup_wizard = MenuItem::with_id(SETUP_WIZARD_ID, "Майстер налаштування", true, None);
    let install_cert = MenuItem::with_id(INSTALL_CERT_ID, "Встановити сертифікат", true, None);
    let uninstall_cert = MenuItem::with_id(UNINSTALL_CERT_ID, "Видалити сертифікат", true, None);
    let rotate_cert = MenuItem::with_id(ROTATE_CERT_ID, "Перевипустити сертифікат", true, None);
    let remove_all = MenuItem::with_id(REMOVE_ALL_ID, "Повністю видалити", true, None);

    // Lifecycle group (Варіант B): pause/resume · restore supervision · [sep]
    // · hide icon · quit.
    let pause_resume_label = if stop_flag_is_set(app_data) {
        RESUME_LABEL
    } else {
        PAUSE_LABEL
    };
    let pause_resume = MenuItem::with_id(PAUSE_RESUME_ID, pause_resume_label, true, None);
    let restore_supervision =
        MenuItem::with_id(RESTORE_SUPERVISION_ID, "Відновити нагляд", true, None);
    let hide_icon = MenuItem::with_id(CLOSE_ID, "Сховати іконку", true, None);
    let quit_app = MenuItem::with_id(QUIT_APP_ID, "Вийти з DNS Quorum Filter", true, None);

    if let Err(err) = menu.append_items(&[
        &open_settings,
        &restart,
        &about,
        &PredefinedMenuItem::separator(),
        &setup_wizard,
        &install_cert,
        &uninstall_cert,
        &rotate_cert,
        &PredefinedMenuItem::separator(),
        &remove_all,
        &PredefinedMenuItem::separator(),
        &pause_resume,
        &restore_supervision,
        &PredefinedMenuItem::separator(),
        &hide_icon,
        &quit_app,
    ]) {
        tracing::warn!("failed to build the full tray menu: {err}");
    }
    (menu, pause_resume)
}

/// Which menu item was clicked — the pure `id -> intent` half of
/// [`handle_menu_event`], split out (T-202) so the routing is table-testable:
/// a mis-typed id constant, or a menu item added with no matching handler,
/// otherwise rides silently in an 823-line binary. Every side effect (confirm
/// dialogs, thread spawns, `control_flow`) stays in `handle_menu_event`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum MenuAction {
    /// Open `/admin/ui` in the default browser.
    OpenSettings,
    /// `POST /admin/reset` — clear the verdict cache and the query log.
    ResetCacheAndLog,
    /// Show the "Про програму" dialog.
    ShowAbout,
    /// Re-enter the first-run setup wizard.
    RunSetupWizard,
    /// Install the local TLS cert into `CurrentUser\Root` (behind a confirm).
    InstallCert,
    /// Remove the local TLS cert from the trust store (behind a confirm).
    UninstallCert,
    /// Regenerate the local TLS cert and re-install it (behind a confirm).
    RotateCert,
    /// Clear the trusted cert + stored secrets, wipe app-data, quit the app.
    RemoveAllLocalState,
    /// Pause filtering if it is running, resume it if paused (`stop.flag`).
    TogglePause,
    /// Relaunch the watchdog if it stopped.
    RestoreSupervision,
    /// Stop the service, the watchdog and this tray.
    QuitApp,
    /// Exit only this tray process; leave the service filtering.
    HideIcon,
    /// An id with no handler — preserves the old catch-all `_ => {}`.
    Unknown,
}

/// Maps a `muda` menu-item id to its [`MenuAction`]. Pure and total.
#[must_use]
fn menu_action_for(id: &str) -> MenuAction {
    match id {
        OPEN_SETTINGS_ID => MenuAction::OpenSettings,
        RESTART_ID => MenuAction::ResetCacheAndLog,
        ABOUT_ID => MenuAction::ShowAbout,
        SETUP_WIZARD_ID => MenuAction::RunSetupWizard,
        INSTALL_CERT_ID => MenuAction::InstallCert,
        UNINSTALL_CERT_ID => MenuAction::UninstallCert,
        ROTATE_CERT_ID => MenuAction::RotateCert,
        REMOVE_ALL_ID => MenuAction::RemoveAllLocalState,
        PAUSE_RESUME_ID => MenuAction::TogglePause,
        RESTORE_SUPERVISION_ID => MenuAction::RestoreSupervision,
        QUIT_APP_ID => MenuAction::QuitApp,
        CLOSE_ID => MenuAction::HideIcon,
        _ => MenuAction::Unknown,
    }
}

fn handle_menu_event(
    id: &str,
    app_data: &Path,
    port: u16,
    control_flow: &mut ControlFlow,
    trust: &TrustState,
) {
    match menu_action_for(id) {
        MenuAction::OpenSettings => {
            browser::open_in_default_browser(&format!("https://127.0.0.1:{port}/admin/ui"));
        }
        MenuAction::ResetCacheAndLog => {
            spawn_admin_action(app_data.to_path_buf(), port, "reset", |client| async move {
                client.reset().await.map(|_response| ())
            });
        }
        MenuAction::ShowAbout => show_about_dialog(),
        MenuAction::RunSetupWizard => run_setup_wizard(app_data, port, trust),
        MenuAction::InstallCert => {
            if confirm_install_cert() {
                let cert_path = app_data.join("cert.pem");
                spawn_cert_action(
                    "install",
                    "Встановити сертифікат",
                    trust,
                    move || ensure_installed(&cert_path).map(|outcome| format!("{outcome:?}")),
                );
            }
        }
        MenuAction::UninstallCert => {
            if confirm_uninstall_cert() {
                spawn_cert_action(
                    "uninstall",
                    "Видалити сертифікат",
                    trust,
                    || uninstall_trust_store().map(|()| "removed".to_string()),
                );
            }
        }
        MenuAction::RotateCert => {
            if confirm_rotate_cert() {
                spawn_cert_action(
                    "rotate",
                    "Перевипустити сертифікат",
                    trust,
                    || rotate_certificate().map(|report| report.to_string()),
                );
            }
        }
        MenuAction::RemoveAllLocalState => {
            if confirm_remove_all_local_state() {
                spawn_remove_all_and_quit(app_data.to_path_buf());
            }
        }
        // T-185 + T-193: pause = write `stop.flag` only. `dnsqb-service` polls
        // it (`pause_watch`) and serves every query through the unfiltered
        // baseline while it exists — the service stays up, the watchdog keeps
        // supervising it. Resume = remove the flag; `ensure_sibling_running` is
        // an idempotent no-op unless both the service and watcher died during
        // the pause. The label the user clicked tells us which.
        MenuAction::TogglePause => {
            if stop_flag_is_set(app_data) {
                clear_stop_flag(app_data);
                ensure_sibling_running(app_data, InstanceRole::Service);
                tracing::info!("filtering resumed by the user");
            } else if confirm_pause() {
                if let Err(err) = set_stop_flag(app_data) {
                    tracing::warn!("could not write stop.flag: {err}");
                }
            }
        }
        // T-185: bring the watchdog back if it stopped (idempotent — a no-op
        // when a watcher is already running). This is the only actionable
        // recovery for a dead watcher; there is no automatic one yet.
        MenuAction::RestoreSupervision => {
            ensure_sibling_running(app_data, InstanceRole::Watcher);
        }
        // T-185: quit the whole app. Write both flags and exit the tray; the
        // watcher picks up `quit.flag` on its next tick, stops the service and
        // exits itself. `stop.flag` covers the gap so nothing is respawned in
        // between.
        MenuAction::QuitApp => {
            if confirm_quit() {
                if let Err(err) = set_stop_flag(app_data) {
                    tracing::warn!("could not write stop.flag: {err}");
                }
                if let Err(err) = set_quit_flag(app_data) {
                    tracing::warn!("could not write quit.flag: {err}");
                }
                *control_flow = ControlFlow::Exit;
            }
        }
        // "Сховати іконку" only exits this process — dnsqb-service and the
        // watcher keep running, filtering stays on. "Вийти з DNS Quorum
        // Filter" above is the one that stops everything.
        MenuAction::HideIcon => *control_flow = ControlFlow::Exit,
        MenuAction::Unknown => {}
    }
}

/// Runs one admin-channel action (`reset`/`shutdown`) on its own throwaway
/// OS thread with its own tiny runtime — these are rare, user-initiated
/// clicks, not a hot path, so building a fresh [`AdminClient`] per call is
/// fine here (same cadence the old `dnsqb-ui` Tauri commands already used) —
/// unlike [`status::spawn`]'s ~30x/minute poll, which specifically must not
/// rebuild one every tick.
fn spawn_admin_action<F, Fut>(app_data: PathBuf, port: u16, action_name: &'static str, action: F)
where
    F: FnOnce(AdminClient) -> Fut + Send + 'static,
    Fut: std::future::Future<Output = Result<(), AdminClientError>>,
{
    std::thread::spawn(move || {
        let Ok(runtime) = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
        else {
            tracing::error!("failed to start a runtime for the {action_name} action");
            return;
        };
        runtime.block_on(async move {
            match AdminClient::new(&app_data, port) {
                Ok(client) => match action(client).await {
                    Ok(()) => tracing::info!("{action_name} succeeded"),
                    Err(err) => tracing::warn!("{action_name} failed: {err}"),
                },
                Err(err) => {
                    tracing::warn!("{action_name} failed to build an admin client: {err}");
                }
            }
        });
    });
}

/// Runs one trust-store action (`install`/`uninstall`) on its own throwaway
/// OS thread — unlike [`spawn_admin_action`], this is a synchronous local
/// `certutil` call, not an admin-HTTP-channel round trip, so no `tokio`
/// runtime is needed at all. Reports the outcome **both** ways: logged (as
/// every other action here does) and via a native dialog on this same
/// thread — this crate builds with `windows_subsystem = "windows"` (no
/// console), so a log line alone is invisible to a user who clicked a menu
/// item and is watching for a result. A silent failure here would leave the
/// user believing a trust-store change succeeded when it didn't — exactly
/// the "no on-screen indication" failure class this crate's own module doc
/// comment already names for "Зупинити фільтрацію" (advisor-caught before
/// commit, not written this way from the start).
fn spawn_trust_store_action<F, E>(action_name: &'static str, dialog_title: &'static str, action: F)
where
    F: FnOnce() -> Result<String, E> + Send + 'static,
    E: std::fmt::Display,
{
    std::thread::spawn(move || match action() {
        Ok(outcome) => {
            tracing::info!("{action_name} succeeded: {outcome}");
            rfd::MessageDialog::new()
                .set_title(dialog_title)
                .set_description(format!("Успішно: {outcome}"))
                .set_level(rfd::MessageLevel::Info)
                .set_buttons(rfd::MessageButtons::Ok)
                .show();
        }
        Err(err) => {
            tracing::warn!("{action_name} failed: {err}");
            rfd::MessageDialog::new()
                .set_title(dialog_title)
                .set_description(format!("Не вдалося: {err}"))
                .set_level(rfd::MessageLevel::Error)
                .set_buttons(rfd::MessageButtons::Ok)
                .show();
        }
    });
}

/// [`spawn_trust_store_action`] plus a trust re-poll after the action returns
/// (T-191) — every cert menu item changes `CurrentUser\Root`, so the status
/// icon's colour needs to catch up. `request_recheck` fires *after* the
/// `certutil` call, not at click time: firing at click would race the
/// ~100–300 ms action and re-poll before the store actually changed.
fn spawn_cert_action<F, E>(
    action_name: &'static str,
    dialog_title: &'static str,
    trust: &TrustState,
    action: F,
) where
    F: FnOnce() -> Result<String, E> + Send + 'static,
    E: std::fmt::Display,
{
    let trust = trust.clone();
    spawn_trust_store_action(action_name, dialog_title, move || {
        let outcome = action();
        trust.request_recheck();
        outcome
    });
}

/// Set by [`spawn_remove_all_and_quit`] once the report dialog is dismissed
/// and the app-data wipe helper is spawned — the event loop exits on its next
/// tick (a worker thread has no handle to `control_flow`).
static QUIT_REQUESTED: AtomicBool = AtomicBool::new(false);

/// T-195 — "Повністю видалити": clear the out-of-tree state, show the report,
/// then bring the whole app down and hand off the rest to the OS.
///
/// Not [`spawn_cert_action`]: the shutdown has to happen *after* the report
/// dialog, and `spawn_cert_action` shows its dialog after the closure returns.
/// Order: [`remove_all_local_state`] (cert + Credential Manager secrets, none
/// of them files in app-data) → report dialog → `stop.flag` + `quit.flag`
/// (the watcher stops `dnsqb-service` and exits on its next tick, exactly like
/// [`QUIT_APP_ID`]) → spawn the detached wipe helper (it waits for every
/// DNS-QF process to exit before deleting) → open Windows Settings →
/// `QUIT_REQUESTED` so this tray exits too.
fn spawn_remove_all_and_quit(app_data: PathBuf) {
    std::thread::spawn(move || {
        let report = format_uninstall_report(&remove_all_local_state(Some(&app_data)));
        tracing::info!("remove-all-local-state finished:\n{report}");
        rfd::MessageDialog::new()
            .set_title("Повністю видалити")
            .set_description(format!(
                "{report}\n\nТека даних застосунку буде повністю видалена, а сам застосунок \
                 закриється. Відкриються Параметри Windows — натисніть «Видалити» на \
                 «dns-quorum-filter», щоб завершити."
            ))
            .set_level(rfd::MessageLevel::Info)
            .set_buttons(rfd::MessageButtons::Ok)
            .show();
        if let Err(err) = set_stop_flag(&app_data) {
            tracing::warn!("could not write stop.flag: {err}");
        }
        if let Err(err) = set_quit_flag(&app_data) {
            tracing::warn!("could not write quit.flag: {err}");
        }
        self_uninstall::spawn_app_data_dir_wipe(&app_data);
        browser::open_windows_apps_settings();
        QUIT_REQUESTED.store(true, Ordering::SeqCst);
    });
}

/// One-shot first-run onboarding offer (T-188). Fires at most once per
/// process (`offered` latch), and only once the trust-watch thread has a
/// *confirmed* `certutil` reading — on a fresh MSIX install `cert.pem` does
/// not exist when the tray starts (T-187), so an earlier check would read the
/// optimistic seed, not the store. [`onboarding::should_offer_onboarding`] is
/// the pure predicate.
fn maybe_offer_onboarding(
    offered: &mut bool,
    app_data: &Path,
    port: u16,
    trust: &TrustState,
    trusted: bool,
) {
    if *offered {
        return;
    }
    let seen = onboarding::onboarding_seen(app_data);
    if onboarding::should_offer_onboarding(trust.is_confirmed(), trusted, seen) {
        *offered = true;
        run_setup_wizard(app_data, port, trust);
    }
}

/// One-shot "point your browser at this" nudge (T-229, detection half only —
/// see `browser_nudge`'s module doc for why rendering isn't wired up yet).
/// Fires at most once **per process** (`offered` latch only) — deliberately
/// does **not** write the persisted `browser-nudge.seen` marker, since
/// nothing is actually shown to the user yet; burning that one-shot latch
/// here would mean the real notification, once a renderer is chosen, could
/// never fire on a machine that already ran this build. `should_offer_
/// browser_nudge` still reads `seen` as an input — a future renderer sets it
/// for real once it renders something.
/// [`browser_nudge::should_offer_browser_nudge`] is the pure predicate.
fn maybe_offer_browser_nudge(offered: &mut bool, app_data: &Path, observed: TrayStatus) {
    if *offered {
        return;
    }
    let total_queries = match observed {
        TrayStatus::Filtering { total, .. } => Some(total),
        _ => None,
    };
    let seen = browser_nudge::browser_nudge_seen(app_data);
    let first_seen = browser_nudge::first_seen(app_data);
    if browser_nudge::should_offer_browser_nudge(SystemTime::now(), first_seen, total_queries, seen)
    {
        *offered = true;
        tracing::info!(
            "no browser appears to have used the local DoH endpoint yet (T-229 nudge condition \
             met — not yet rendered, see browser_nudge's module doc)"
        );
    }
}

/// Set while a [`run_setup_wizard`] welcome dialog is open, so the auto-offer
/// and the "Майстер налаштування" menu item can't stack two modal dialogs
/// (each able to spawn its own `ensure_installed`).
static WIZARD_ACTIVE: AtomicBool = AtomicBool::new(false);

/// The first-run wizard (T-188): a welcome dialog offering to install the
/// local certificate, then — on «Так» and a successful install — open the
/// browser-setup page. Runs entirely on a throwaway thread because `rfd`
/// dialogs block and both callers (the auto-offer above and the "Майстер
/// налаштування" menu item) are on the event-loop thread. Reuses
/// [`spawn_cert_action`] for the install half, so the trust icon re-polls
/// afterward for free. `onboarding.seen` is written on «Пізніше» and on a
/// *successful* install, never on a failed one (that should re-offer next
/// launch); the menu item is the manual re-entry regardless.
fn run_setup_wizard(app_data: &Path, port: u16, trust: &TrustState) {
    if WIZARD_ACTIVE.swap(true, Ordering::SeqCst) {
        return; // a welcome dialog is already open
    }
    let app_data = app_data.to_path_buf();
    let trust = trust.clone();
    std::thread::spawn(move || {
        let proceed = rfd::MessageDialog::new()
            .set_title("Ласкаво просимо до DNS Quorum Filter")
            .set_description(
                "Залишилось два кроки, щоб браузер почав фільтрувати DNS:\n\n\
                 1. Встановити локальний сертифікат — без нього браузер не довірятиме \
                 сторінці налаштувань.\n\
                 2. Вказати адресу локального фільтра в налаштуваннях браузера — \
                 сторінка з інструкцією відкриється після кроку 1.\n\n\
                 Встановити сертифікат зараз?",
            )
            .set_level(rfd::MessageLevel::Info)
            .set_buttons(rfd::MessageButtons::YesNo)
            .show();
        WIZARD_ACTIVE.store(false, Ordering::SeqCst);
        if proceed != rfd::MessageDialogResult::Yes {
            onboarding::mark_onboarding_seen(&app_data);
            return;
        }
        let cert_path = app_data.join("cert.pem");
        let url = format!("https://127.0.0.1:{port}/admin/ui");
        spawn_cert_action(
            "onboarding-install",
            "Встановити сертифікат",
            &trust,
            move || -> Result<String, dnsqb_service::TrustStoreError> {
                let outcome = ensure_installed(&cert_path)?;
                // Reached only on a successful install — a failure bails on the
                // `?` above with the marker still unwritten.
                onboarding::mark_onboarding_seen(&app_data);
                browser::open_in_default_browser(&url);
                Ok(format!("{outcome:?}"))
            },
        );
    });
}

/// Native confirm dialog before `certutil -addstore` — this pops the OS's
/// own confirmation dialog too (a second, separate prompt) unless/until
/// T-49's open "is certutil silent?" question is settled by a real run; see
/// `trust_store.rs`'s module doc comment.
fn confirm_install_cert() -> bool {
    let result = rfd::MessageDialog::new()
        .set_title("Встановити сертифікат")
        .set_description(
            "Локальний сертифікат dns-quorum-filter буде додано до довірених кореневих \
             сертифікатів поточного користувача (CurrentUser\\Root). Це прибирає попередження \
             браузера про недовірений сертифікат на сторінці налаштувань. Windows може показати \
             власний діалог підтвердження. Продовжити?",
        )
        .set_level(rfd::MessageLevel::Info)
        .set_buttons(rfd::MessageButtons::YesNo)
        .show();
    result == rfd::MessageDialogResult::Yes
}

/// Native confirm dialog before `certutil -delstore` — names the real
/// consequence (browser warning returns), same pattern as [`confirm_pause`].
fn confirm_uninstall_cert() -> bool {
    let result = rfd::MessageDialog::new()
        .set_title("Видалити сертифікат")
        .set_description(
            "Локальний сертифікат dns-quorum-filter буде видалено з довірених кореневих \
             сертифікатів. Браузер знову покаже попередження про недовірений сертифікат на \
             сторінці налаштувань, доки сертифікат не буде встановлено повторно. Продовжити?",
        )
        .set_level(rfd::MessageLevel::Warning)
        .set_buttons(rfd::MessageButtons::YesNo)
        .show();
    result == rfd::MessageDialogResult::Yes
}

/// Native confirm dialog before certificate rotation — names every consequence
/// *before* the user acts: the old `CurrentUser\Root` entries are removed, a
/// fresh key is generated and the new certificate installed in their place, and
/// the running `dnsqb-service` keeps serving the *previous* certificate (it
/// holds its TLS config from startup) until it is restarted. In that window the
/// browser shows an untrusted-certificate warning on `/admin/ui` because the
/// certificate on the wire is no longer in the trust store; restarting
/// `dnsqb-service` clears it. (The tray's own status poll is unaffected —
/// [`status::spawn`] keeps its cached client, still pinned to and matching the
/// still-served previous certificate.)
fn confirm_rotate_cert() -> bool {
    let result = rfd::MessageDialog::new()
        .set_title("Перевипустити сертифікат")
        .set_description(
            "Буде згенеровано новий локальний сертифікат dns-quorum-filter із новим ключем. \
             Старі записи цього проєкту прибираються з довірених кореневих сертифікатів \
             (CurrentUser\\Root), новий сертифікат встановлюється замість них. \
             dnsqb-service потрібно перезапустити, щоб новий сертифікат почав діяти — до \
             перезапуску сервіс віддає попередній сертифікат, і браузер показуватиме \
             попередження про недовірений сертифікат на сторінці налаштувань. Після \
             перезапуску воно зникає. Продовжити?",
        )
        .set_level(rfd::MessageLevel::Warning)
        .set_buttons(rfd::MessageButtons::YesNo)
        .show();
    result == rfd::MessageDialogResult::Yes
}

/// Native confirm dialog before T-70/T-195's full removal — names everything
/// it clears (the trusted certificate, the three Credential Manager secrets,
/// **and** the whole app-data directory) and what happens next: the app
/// closes and Windows Settings opens for the final "Remove" click (MSIX,
/// T-156, gives the app no uninstall-time hook of its own).
fn confirm_remove_all_local_state() -> bool {
    let result = rfd::MessageDialog::new()
        .set_title("Повністю видалити")
        .set_description(
            "Буде повністю видалено локальні дані dns-quorum-filter: довірений сертифікат, \
             TLS-ключ, ключ шифрування журналу/кешу та збережені креденшели MaxMind зі сховища \
             облікових даних Windows, а також уся тека даних застосунку (журнал, кеш, \
             налаштування). Застосунок закриється, і відкриються Параметри Windows — там \
             натисніть «Видалити» на dns-quorum-filter. Продовжити?",
        )
        .set_level(rfd::MessageLevel::Warning)
        .set_buttons(rfd::MessageButtons::YesNo)
        .show();
    result == rfd::MessageDialogResult::Yes
}

/// One line per artifact, never a single collapsed pass/fail — the same
/// discipline [`UninstallReport`] itself follows.
fn format_uninstall_report(report: &UninstallReport) -> String {
    fn line(label: &str, outcome: ArtifactOutcome) -> String {
        let text = match outcome {
            ArtifactOutcome::Removed => "видалено",
            ArtifactOutcome::NotPresent => "не було встановлено",
            ArtifactOutcome::Failed(_) => "НЕ ВДАЛОСЯ видалити",
        };
        format!("{label}: {text}")
    }
    [
        line("Сертифікат", report.cert),
        line("TLS-ключ", report.tls_key),
        line("Ключ шифрування", report.persistence_key),
        line("Креденшели MaxMind", report.maxmind_creds),
        line("Ключ особистої зони", report.personal_zone_key),
    ]
    .join("\n")
}

fn show_about_dialog() {
    rfd::MessageDialog::new()
        .set_title("dns-quorum-filter")
        .set_description(format!(
            "dnsqb-tray {}\nЛіцензія: Apache-2.0\nЛокальний DoH quorum-фільтр \u{2014} \
             https://127.0.0.1/admin/ui",
            env!("CARGO_PKG_VERSION")
        ))
        .set_level(rfd::MessageLevel::Info)
        .set_buttons(rfd::MessageButtons::Ok)
        .show();
}

/// Native confirm dialog before pausing filtering (T-185 / T-193). Names the
/// consequence precisely: DNS keeps working (the service stays up, T-193), but
/// quorum + `GeoIP` stop applying — the user's own lists still do. Reversible
/// from the same menu, and a fresh app launch also clears `stop.flag`, so the
/// dialog says so. Deliberately does **not** claim "everything goes unfiltered"
/// — a blocklisted domain is still blocked during a pause.
fn confirm_pause() -> bool {
    let result = rfd::MessageDialog::new()
        .set_title("Призупинити фільтрацію")
        .set_description(
            "DNS продовжить працювати, але фільтрацію буде вимкнено: quorum-перевірка та \
             GeoIP не застосовуватимуться, домени резолвитимуться напряму через \
             baseline-резолвер. Ваші власні списки блокування та дозволу продовжать діяти. \
             Відновити — цим самим пунктом меню або перезапуском застосунку. Продовжити?",
        )
        .set_level(rfd::MessageLevel::Warning)
        .set_buttons(rfd::MessageButtons::YesNo)
        .show();
    result == rfd::MessageDialogResult::Yes
}

/// Native confirm dialog before quitting the whole app (T-185) — this stops
/// the service, the watchdog and the tray. Same blast-radius warning shape as
/// [`confirm_pause`], stronger wording.
fn confirm_quit() -> bool {
    let result = rfd::MessageDialog::new()
        .set_title("Вийти з DNS Quorum Filter")
        .set_description(
            "Застосунок повністю зупиниться: DNS-фільтрація, фоновий нагляд і ця іконка. \
             DNS піде нефільтрованим, доки ви знову не запустите застосунок із меню Пуск. \
             Продовжити?",
        )
        .set_level(rfd::MessageLevel::Warning)
        .set_buttons(rfd::MessageButtons::YesNo)
        .show();
    result == rfd::MessageDialogResult::Yes
}

#[cfg(test)]
mod tests {
    use super::{format_uninstall_report, menu_action_for, MenuAction};
    use dnsqb_service::{ArtifactOutcome, UninstallReport};

    // Keyed on the literal id strings `build_menu` passes to
    // `MenuItem::with_id`, NOT the `*_ID` constants — so a constant silently
    // changing value is caught here even though a constant-keyed table would
    // still pass (it would reference the same changed constant on both sides).
    #[test]
    fn menu_action_for_maps_each_built_menu_id_to_its_action() {
        let cases = [
            ("open-settings", MenuAction::OpenSettings),
            ("restart", MenuAction::ResetCacheAndLog),
            ("about", MenuAction::ShowAbout),
            ("setup-wizard", MenuAction::RunSetupWizard),
            ("install-cert", MenuAction::InstallCert),
            ("uninstall-cert", MenuAction::UninstallCert),
            ("rotate-cert", MenuAction::RotateCert),
            ("remove-all-local-state", MenuAction::RemoveAllLocalState),
            ("pause-resume-filtering", MenuAction::TogglePause),
            ("restore-supervision", MenuAction::RestoreSupervision),
            ("quit-app", MenuAction::QuitApp),
            ("close", MenuAction::HideIcon),
        ];
        for (id, expected) in cases {
            assert_eq!(menu_action_for(id), expected, "id {id:?}");
        }
    }

    #[test]
    fn menu_action_for_unrecognised_ids_are_unknown() {
        for id in ["", "not-a-real-id", "open-setting", "OPEN-SETTINGS", "quit"] {
            assert_eq!(menu_action_for(id), MenuAction::Unknown, "id {id:?}");
        }
    }

    fn report_of(outcome: ArtifactOutcome) -> UninstallReport {
        UninstallReport {
            cert: outcome,
            tls_key: outcome,
            persistence_key: outcome,
            maxmind_creds: outcome,
            personal_zone_key: outcome,
        }
    }

    #[test]
    fn uninstall_report_has_one_labelled_line_per_artifact() {
        let text = format_uninstall_report(&report_of(ArtifactOutcome::Removed));
        assert_eq!(text.lines().count(), 5);
        for label in [
            "Сертифікат",
            "TLS-ключ",
            "Ключ шифрування",
            "Креденшели MaxMind",
            "Ключ особистої зони",
        ] {
            assert!(text.contains(label), "missing label {label}");
        }
    }

    #[test]
    fn uninstall_report_maps_each_outcome_to_its_phrase() {
        assert!(
            format_uninstall_report(&report_of(ArtifactOutcome::Removed))
                .lines()
                .all(|line| line.ends_with(": видалено"))
        );
        assert!(
            format_uninstall_report(&report_of(ArtifactOutcome::NotPresent))
                .lines()
                .all(|line| line.ends_with(": не було встановлено"))
        );
        assert!(
            format_uninstall_report(&report_of(ArtifactOutcome::Failed("x")))
                .lines()
                .all(|line| line.ends_with(": НЕ ВДАЛОСЯ видалити"))
        );
    }

    #[test]
    fn uninstall_report_renders_each_field_independently() {
        let text = format_uninstall_report(&UninstallReport {
            cert: ArtifactOutcome::Removed,
            tls_key: ArtifactOutcome::NotPresent,
            persistence_key: ArtifactOutcome::Failed("secret store error"),
            maxmind_creds: ArtifactOutcome::Removed,
            personal_zone_key: ArtifactOutcome::NotPresent,
        });
        let lines: Vec<&str> = text.lines().collect();
        assert_eq!(
            lines,
            vec![
                "Сертифікат: видалено",
                "TLS-ключ: не було встановлено",
                "Ключ шифрування: НЕ ВДАЛОСЯ видалити",
                "Креденшели MaxMind: видалено",
                "Ключ особистої зони: не було встановлено",
            ]
        );
    }
}
