#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]
#![forbid(unsafe_code)]
#![warn(clippy::pedantic)]
#![deny(clippy::unwrap_used, clippy::expect_used)]

//! `dnsqb-tray` (T-149) — a lightweight background tray icon replacing the
//! Tauri desktop window (T-52, `dnsqb-ui`, deleted alongside this crate's
//! introduction). Unlike `dnsqb-ui`, this is a genuine long-running
//! background process (SERVICES.md), started once (manually today — T-150
//! tracks real autostart, separately) and then left running: its whole job
//! is showing live resolver status in the tray tooltip and giving a
//! mouse-only user five actions without ever opening a terminal. Full
//! configuration moved to the browser (`dnsqb-service`'s own embedded
//! `/admin/ui`, T-149) — this crate has no window of its own.
//!
//! "Закрити" and "Зупинити фільтрацію" are deliberately two separate menu
//! items, not one (advisor-caught during the T-149 plan review): this tray
//! never owns `dnsqb-service` as a child process (T-150's own scoping
//! reasoning — a headless target can't depend on a graphical tray
//! supervisor to launch it), so a single "close = stop everything" action
//! would leave DNS silently unfiltered with no on-screen indication at all
//! once the tray itself is gone — the Три Б failure mode by name. "Закрити"
//! only exits this process; `dnsqb-service` keeps running. "Зупинити
//! фільтрацію" is the one action that actually calls `POST
//! /admin/shutdown`, gated behind a native confirm dialog naming that
//! consequence.
//!
//! Threading model (T-149 Крок 0, confirmed against a throwaway scratch
//! probe before writing this crate for real): `tao`'s [`EventLoop::run`]
//! hijacks the calling thread forever and is not itself `async` — so
//! polling `dnsqb-service`'s admin channel lives on a separate OS thread
//! with its own single-threaded `tokio` runtime ([`status::spawn`]),
//! publishing results the main thread reads without ever blocking on
//! network I/O itself. `muda`'s [`MenuEvent`] channel is a plain
//! lock-free queue, not wired into `tao`'s own event delivery on Windows
//! (only macOS/Linux integrate it via the native run loop, per `tray-icon`'s
//! own docs) — this loop drains it on a short fixed [`EVENT_POLL_INTERVAL`]
//! tick via `ControlFlow::WaitUntil` instead.

mod browser;
mod browser_nudge;
mod i18n;
mod nudge_popup;
mod onboarding;
mod self_uninstall;
mod status;

use dnsqb_service::{
    acquire_instance_guard, app_data_dir, clear_stop_flag, ensure_sibling_running, init_logging,
    set_quit_flag, set_stop_flag, stop_flag_is_set, write_pid_file, AdminClient, AdminClientError,
    GuardError, InstanceGuard, InstanceRole, ResolverConfig,
};
use dnsqb_service::{
    ensure_installed, remove_all_local_state, rotate_certificate,
    uninstall as uninstall_trust_store, ArtifactOutcome, TrustStoreOutcome, UninstallReport,
};
use status::{IconColour, TrayStatus, TrustState};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::{Duration, Instant, SystemTime};
use tao::event_loop::{ControlFlow, EventLoop};
use tray_icon::menu::{Menu, MenuEvent, MenuItem, PredefinedMenuItem};
use tray_icon::{Icon, TrayIcon, TrayIconBuilder};

// Four raw 32x32 RGBA blobs (4096 bytes each, no header), transparent
// background + a hexagon glyph in the per-status colour (green / amber / grey
// / red) — `tray_icon::Icon::from_rgba` takes raw pixels, not an encoded
// image, so compiling the blobs in avoids both a runtime filesystem read and
// an image-decode dependency (the same "everything in, no runtime asset I/O"
// choice `admin_ui.rs` makes for the embedded web UI). Generated by
// `assets/gen-icon.py` (`make_tray_glyph(size, colour)`), the single source
// for every project icon — re-run that script to regenerate, never hand-edit
// a .bin (T-191, extending T-183's single white glyph). `status::icon_colour`
// picks which one from the live `TrayStatus` + cert-trust state.
const ICON_GREEN: &[u8] = include_bytes!("../icons/tray-32-green-rgba.bin");
const ICON_AMBER: &[u8] = include_bytes!("../icons/tray-32-amber-rgba.bin");
const ICON_GREY: &[u8] = include_bytes!("../icons/tray-32-grey-rgba.bin");
const ICON_RED: &[u8] = include_bytes!("../icons/tray-32-red-rgba.bin");
const ICON_SIZE: u32 = 32;

/// The four decoded status icons, built once at startup. `tray_icon::Icon` is
/// `Clone`, so [`Self::get`] hands `set_icon` an owned copy per update.
struct TrayIcons {
    green: Icon,
    amber: Icon,
    grey: Icon,
    red: Icon,
}

impl TrayIcons {
    /// Decodes all four build-time blobs. `None` on any failure — a build-time
    /// asset that won't decode is fatal, the same handling the pre-T-191
    /// single-icon path had.
    fn build() -> Option<Self> {
        let decode = |bytes: &[u8]| Icon::from_rgba(bytes.to_vec(), ICON_SIZE, ICON_SIZE).ok();
        Some(Self {
            green: decode(ICON_GREEN)?,
            amber: decode(ICON_AMBER)?,
            grey: decode(ICON_GREY)?,
            red: decode(ICON_RED)?,
        })
    }

    fn get(&self, colour: IconColour) -> Icon {
        match colour {
            IconColour::Green => self.green.clone(),
            IconColour::Amber => self.amber.clone(),
            IconColour::Grey => self.grey.clone(),
            IconColour::Red => self.red.clone(),
        }
    }
}

const OPEN_SETTINGS_ID: &str = "open-settings";
const RESTART_ID: &str = "restart";
const ABOUT_ID: &str = "about";
const PAUSE_RESUME_ID: &str = "pause-resume-filtering";
const RESTORE_SUPERVISION_ID: &str = "restore-supervision";
const QUIT_APP_ID: &str = "quit-app";
const CLOSE_ID: &str = "close";
const SETUP_WIZARD_ID: &str = "setup-wizard";
const INSTALL_CERT_ID: &str = "install-cert";
const UNINSTALL_CERT_ID: &str = "uninstall-cert";
const ROTATE_CERT_ID: &str = "rotate-cert";
const REMOVE_ALL_ID: &str = "remove-all-local-state";

/// Re-check cadence for `muda`'s global menu-event channel (see the module
/// doc comment for why this loop drives it rather than `tao` itself) —
/// independent of [`status::spawn`]'s own 2s poll interval; this tick only
/// governs how quickly a menu click gets noticed.
const EVENT_POLL_INTERVAL: Duration = Duration::from_millis(100);

/// How often the event loop re-stats `stop.flag` to keep the pause/resume
/// label current (T-185). The flag only changes on a click handled here or a
/// fresh watcher launch clearing it, so statting it on every 100 ms
/// [`EVENT_POLL_INTERVAL`] tick is far more often than needed (advisor,
/// Батч 3.12 closing).
const FLAG_CHECK_INTERVAL: Duration = Duration::from_secs(1);

/// The single-instance guard, pid file, watcher safety-net, and config load
/// `main` needs before it can build anything — extracted only to keep `main`
/// itself under clippy's line-count lint (same "cohesive extracted helper"
/// discipline as `refresh_tray`/`maybe_offer_onboarding`, not a behaviour
/// change). Exits the process on any unrecoverable failure, exactly as this
/// code did inline; `None` is only the expected "another instance is
/// already running" idempotent exit, not an error.
fn bootstrap(app_data: &Path) -> Option<(InstanceGuard, u16)> {
    // SPEC.md §7.1 #2/#3: one tray per app-data directory, and a `tray.pid`
    // the watcher's launcher reads to decide whether to spawn one (T-150) —
    // without it, every watcher (re)start would spawn another tray. A second
    // instance (a double-clicked shortcut, the watcher relaunching) just
    // exits; that is the idempotent-launcher behaviour, not an error. `tao`'s
    // event loop never returns, so the guard is released by the OS on exit
    // (its whole `share_mode(0)` design) rather than by `Drop`.
    let guard = match acquire_instance_guard(app_data, InstanceRole::Tray) {
        Ok(guard) => guard,
        Err(GuardError::AlreadyRunning(_)) => {
            tracing::info!("another dnsqb-tray instance is already running, exiting");
            return None;
        }
        Err(err) => {
            tracing::error!("could not acquire the tray single-instance lock: {err}");
            std::process::exit(1);
        }
    };
    if let Err(err) = write_pid_file(app_data, InstanceRole::Tray) {
        tracing::warn!("could not write the tray pid file: {err}");
    }

    // T-187 safety net: normally the watcher spawns this tray, so a watcher is
    // already up. But if `dnsqb-tray.exe` was launched on its own (a stray
    // double-click of the wrong file), bring the watcher up so the user isn't
    // left with an unsupervised or absent service. Not an inversion of the
    // hierarchy — the watcher stays the root; this is idempotent and a no-op
    // when a watcher is already running.
    ensure_sibling_running(app_data, InstanceRole::Watcher);

    let port = match ResolverConfig::load(&app_data.join("resolver_config.toml")) {
        Ok(config) => config.port,
        Err(err) => {
            tracing::error!("failed to load resolver_config.toml: {err}");
            std::process::exit(1);
        }
    };
    Some((guard, port))
}

fn main() {
    // T-235 Батч 5.6: checked before anything else - no app-data dir, no
    // logging, no single-instance guard. `dnsqb_service::cli_help`'s own
    // module doc explains why plain `println!` is safe here even in a
    // `windows_subsystem = "windows"` release build (empirically verified).
    if dnsqb_service::wants_help(std::env::args().skip(1)) {
        println!(
            "{}",
            dnsqb_service::help_text(dnsqb_service::CliHelpBinary::Tray)
        );
        return;
    }

    // T-151 Батч 5.5: detected once at startup, then threaded explicitly
    // through every function that needs translated text - see `i18n.rs`'s
    // own module doc comment for why this is never read from ambient global
    // state instead.
    let locale = i18n::detect_locale();

    let app_data = match app_data_dir() {
        Ok(dir) => {
            init_logging("dnsqb-tray", Some(&dir)); // T-184
            dir
        }
        Err(err) => {
            init_logging("dnsqb-tray", None);
            tracing::error!("no app-data directory available, dnsqb-tray cannot run: {err}");
            std::process::exit(1);
        }
    };

    let Some((_guard, port)) = bootstrap(&app_data) else {
        return;
    };

    // T-229: the earliest-launch stamp for the browser-nudge threshold below
    // must be written unconditionally at every startup (idempotent — only the
    // first call ever actually creates the file), not lazily on first poll
    // tick, so a tray that never reaches a later tick still has it recorded.
    browser_nudge::mark_first_seen_if_absent(&app_data, SystemTime::now());

    let status_handle = status::spawn(app_data.clone(), port);
    let trust = status::spawn_trust_watch(app_data.join("cert.pem"));

    let (tray_icon, icons, pause_resume_item) = build_tray_icon(&app_data, locale);

    let menu_channel = MenuEvent::receiver();
    let mut refresh_state = TrayRefreshState {
        status: TrayStatus::Unreachable,
        trusted: trust.is_trusted(),
        colour: IconColour::Red,
    };
    let mut last_paused = stop_flag_is_set(&app_data);
    let mut last_flag_check = Instant::now();
    let mut onboarding_offered = false;
    let mut browser_nudge_offered = false;
    let mut browser_nudge_popup: Option<nudge_popup::NudgePopup> = None;

    let event_loop: EventLoop<()> = EventLoop::new();
    event_loop.run(move |event, target, control_flow| {
        *control_flow = ControlFlow::WaitUntil(Instant::now() + EVENT_POLL_INTERVAL);

        // T-195: the "Повністю видалити" worker sets this once the report
        // dialog is dismissed and the wipe helper is spawned. Checked after
        // the `WaitUntil` assignment above so it isn't overwritten; the
        // `return` drops this tick's queued menu event, which is fine here
        // (do not copy this pattern to the pause/label path).
        if QUIT_REQUESTED.load(Ordering::SeqCst) {
            *control_flow = ControlFlow::Exit;
            return;
        }

        let observed = status_handle.current();
        let trusted = trust.is_trusted();
        refresh_tray(
            &tray_icon,
            &icons,
            observed,
            trusted,
            locale,
            &mut refresh_state,
        );
        maybe_offer_onboarding(
            &mut onboarding_offered,
            &app_data,
            port,
            &trust,
            trusted,
            locale,
        );
        drive_browser_nudge(
            &mut browser_nudge_offered,
            &app_data,
            observed,
            target,
            &tray_icon,
            &event,
            &mut browser_nudge_popup,
        );

        // T-185: flip the pause/resume label when `stop.flag` appears or is
        // removed (by this menu, or by a fresh watcher launch clearing it) —
        // re-stat it at most once a second, not on every 100 ms tick.
        if last_flag_check.elapsed() >= FLAG_CHECK_INTERVAL {
            last_flag_check = Instant::now();
            let paused = stop_flag_is_set(&app_data);
            if paused != last_paused {
                let label = if paused {
                    i18n::t(locale, "menu.resume")
                } else {
                    i18n::t(locale, "menu.pause")
                };
                pause_resume_item.set_text(&label);
                last_paused = paused;
            }
        }

        if let Ok(event) = menu_channel.try_recv() {
            handle_menu_event(
                event.id().as_ref(),
                &app_data,
                port,
                control_flow,
                &trust,
                locale,
            );
        }
    });
}

/// The three "last observed" fields [`refresh_tray`] diffs the fresh poll
/// result against — grouped into one cohesive struct (clippy
/// `too_many_arguments`, fixed structurally per this project's own
/// convention, not `#[allow]`) rather than three separate `&mut` parameters.
struct TrayRefreshState {
    status: TrayStatus,
    trusted: bool,
    colour: IconColour,
}

/// Tooltip + icon refresh on one event-loop tick (T-191). The tooltip is
/// driven by `(observed, trusted)` — not `observed` alone — so that clicking
/// "Встановити сертифікат" while filtering, which flips only `trusted`, still
/// re-renders it (the cert-warning suffix, [`status::compose_tooltip`]). A
/// failed `set_tooltip` is cosmetic and self-heals on the next change, so
/// `last_status`/`last_trusted` commit unconditionally; `last_colour` commits
/// **only on `set_icon` success**, or one transient failure would make the
/// `colour != *last_colour` guard read equal forever and pin the wrong colour.
fn refresh_tray(
    tray_icon: &TrayIcon,
    icons: &TrayIcons,
    observed: TrayStatus,
    trusted: bool,
    locale: &str,
    state: &mut TrayRefreshState,
) {
    if observed != state.status || trusted != state.trusted {
        let tooltip = status::compose_tooltip(observed, trusted, locale);
        if let Err(err) = tray_icon.set_tooltip(Some(tooltip)) {
            tracing::warn!("failed to update tray tooltip: {err}");
        }
        state.status = observed;
        state.trusted = trusted;
    }

    let colour = status::icon_colour(observed, trusted);
    if colour != state.colour {
        match tray_icon.set_icon(Some(icons.get(colour))) {
            Ok(()) => state.colour = colour,
            Err(err) => tracing::warn!("failed to update tray icon colour: {err}"),
        }
    }
}

/// Builds the tray icon (all four colour variants + the initial red/
/// unreachable frame) and its menu — extracted only to keep `main` under
/// clippy's line-count lint (same "cohesive extracted helper" discipline as
/// [`bootstrap`]), not a behaviour change. Exits the process on any
/// unrecoverable failure, exactly as this code did inline.
fn build_tray_icon(app_data: &Path, locale: &str) -> (TrayIcon, TrayIcons, MenuItem) {
    let Some(icons) = TrayIcons::build() else {
        tracing::error!(
            "an embedded tray icon failed to decode - these are build-time assets, not user input"
        );
        std::process::exit(1);
    };
    let (menu, pause_resume_item) = build_menu(app_data, locale);
    // Start on red, matching the initial `TrayStatus::Unreachable` tooltip
    // below — icon and tooltip agree from the first frame.
    let tray_icon = match TrayIconBuilder::new()
        .with_menu(Box::new(menu))
        .with_icon(icons.get(IconColour::Red))
        .with_tooltip(TrayStatus::Unreachable.tooltip(locale))
        .build()
    {
        Ok(tray_icon) => tray_icon,
        Err(err) => {
            tracing::error!("failed to create the tray icon: {err}");
            std::process::exit(1);
        }
    };
    (tray_icon, icons, pause_resume_item)
}

/// Builds the tray menu and returns it together with a handle to the
/// pause/resume item, whose label the event loop flips between
/// `t(locale, "menu.pause")` and `t(locale, "menu.resume")` as `stop.flag`
/// comes and goes (T-185; T-151 Батч 5.5 — used to be two fixed constants).
fn build_menu(app_data: &Path, locale: &str) -> (Menu, MenuItem) {
    let menu = Menu::new();
    let open_settings = MenuItem::with_id(
        OPEN_SETTINGS_ID,
        i18n::t(locale, "menu.openSettings"),
        true,
        None,
    );
    let restart = MenuItem::with_id(
        RESTART_ID,
        i18n::t(locale, "menu.resetCacheLog"),
        true,
        None,
    );
    let about = MenuItem::with_id(ABOUT_ID, i18n::t(locale, "menu.about"), true, None);
    let setup_wizard = MenuItem::with_id(
        SETUP_WIZARD_ID,
        i18n::t(locale, "menu.setupWizard"),
        true,
        None,
    );
    let install_cert = MenuItem::with_id(
        INSTALL_CERT_ID,
        i18n::t(locale, "menu.installCert"),
        true,
        None,
    );
    let uninstall_cert = MenuItem::with_id(
        UNINSTALL_CERT_ID,
        i18n::t(locale, "menu.uninstallCert"),
        true,
        None,
    );
    let rotate_cert = MenuItem::with_id(
        ROTATE_CERT_ID,
        i18n::t(locale, "menu.rotateCert"),
        true,
        None,
    );
    let remove_all =
        MenuItem::with_id(REMOVE_ALL_ID, i18n::t(locale, "menu.removeAll"), true, None);

    // Lifecycle group (Варіант B): pause/resume · restore supervision · [sep]
    // · hide icon · quit.
    let pause_resume_label = if stop_flag_is_set(app_data) {
        i18n::t(locale, "menu.resume")
    } else {
        i18n::t(locale, "menu.pause")
    };
    let pause_resume = MenuItem::with_id(PAUSE_RESUME_ID, pause_resume_label, true, None);
    let restore_supervision = MenuItem::with_id(
        RESTORE_SUPERVISION_ID,
        i18n::t(locale, "menu.restoreSupervision"),
        true,
        None,
    );
    let hide_icon = MenuItem::with_id(CLOSE_ID, i18n::t(locale, "menu.hideIcon"), true, None);
    let quit_app = MenuItem::with_id(QUIT_APP_ID, i18n::t(locale, "menu.quitApp"), true, None);

    if let Err(err) = menu.append_items(&[
        &open_settings,
        &restart,
        &about,
        &PredefinedMenuItem::separator(),
        &setup_wizard,
        &install_cert,
        &uninstall_cert,
        &rotate_cert,
        &PredefinedMenuItem::separator(),
        &remove_all,
        &PredefinedMenuItem::separator(),
        &pause_resume,
        &restore_supervision,
        &PredefinedMenuItem::separator(),
        &hide_icon,
        &quit_app,
    ]) {
        tracing::warn!("failed to build the full tray menu: {err}");
    }
    (menu, pause_resume)
}

/// Which menu item was clicked — the pure `id -> intent` half of
/// [`handle_menu_event`], split out (T-202) so the routing is table-testable:
/// a mis-typed id constant, or a menu item added with no matching handler,
/// otherwise rides silently in an 823-line binary. Every side effect (confirm
/// dialogs, thread spawns, `control_flow`) stays in `handle_menu_event`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum MenuAction {
    /// Open `/admin/ui` in the default browser.
    OpenSettings,
    /// `POST /admin/reset` — clear the verdict cache and the query log.
    ResetCacheAndLog,
    /// Show the "Про програму" dialog.
    ShowAbout,
    /// Re-enter the first-run setup wizard.
    RunSetupWizard,
    /// Install the local TLS cert into `CurrentUser\Root` (behind a confirm).
    InstallCert,
    /// Remove the local TLS cert from the trust store (behind a confirm).
    UninstallCert,
    /// Regenerate the local TLS cert and re-install it (behind a confirm).
    RotateCert,
    /// Clear the trusted cert + stored secrets, wipe app-data, quit the app.
    RemoveAllLocalState,
    /// Pause filtering if it is running, resume it if paused (`stop.flag`).
    TogglePause,
    /// Relaunch the watchdog if it stopped.
    RestoreSupervision,
    /// Stop the service, the watchdog and this tray.
    QuitApp,
    /// Exit only this tray process; leave the service filtering.
    HideIcon,
    /// An id with no handler — preserves the old catch-all `_ => {}`.
    Unknown,
}

/// Maps a `muda` menu-item id to its [`MenuAction`]. Pure and total.
#[must_use]
fn menu_action_for(id: &str) -> MenuAction {
    match id {
        OPEN_SETTINGS_ID => MenuAction::OpenSettings,
        RESTART_ID => MenuAction::ResetCacheAndLog,
        ABOUT_ID => MenuAction::ShowAbout,
        SETUP_WIZARD_ID => MenuAction::RunSetupWizard,
        INSTALL_CERT_ID => MenuAction::InstallCert,
        UNINSTALL_CERT_ID => MenuAction::UninstallCert,
        ROTATE_CERT_ID => MenuAction::RotateCert,
        REMOVE_ALL_ID => MenuAction::RemoveAllLocalState,
        PAUSE_RESUME_ID => MenuAction::TogglePause,
        RESTORE_SUPERVISION_ID => MenuAction::RestoreSupervision,
        QUIT_APP_ID => MenuAction::QuitApp,
        CLOSE_ID => MenuAction::HideIcon,
        _ => MenuAction::Unknown,
    }
}

fn handle_menu_event(
    id: &str,
    app_data: &Path,
    port: u16,
    control_flow: &mut ControlFlow,
    trust: &TrustState,
    locale: &str,
) {
    match menu_action_for(id) {
        MenuAction::OpenSettings => {
            browser::open_in_default_browser(&format!("https://127.0.0.1:{port}/admin/ui"));
        }
        MenuAction::ResetCacheAndLog => {
            spawn_admin_action(app_data.to_path_buf(), port, "reset", |client| async move {
                client.reset().await.map(|_response| ())
            });
        }
        MenuAction::ShowAbout => show_about_dialog(port, locale),
        MenuAction::RunSetupWizard => run_setup_wizard(app_data, port, trust, locale),
        MenuAction::InstallCert => {
            if confirm_install_cert(locale) {
                let cert_path = app_data.join("cert.pem");
                let locale = locale.to_string();
                spawn_cert_action(
                    "install",
                    dialog_title(&i18n::t(&locale, "menu.installCert")),
                    locale.clone(),
                    trust,
                    move || {
                        ensure_installed(&cert_path)
                            .map(|outcome| trust_store_outcome_text(outcome, &locale))
                    },
                );
            }
        }
        MenuAction::UninstallCert => {
            if confirm_uninstall_cert(locale) {
                let locale = locale.to_string();
                spawn_cert_action(
                    "uninstall",
                    dialog_title(&i18n::t(&locale, "menu.uninstallCert")),
                    locale.clone(),
                    trust,
                    move || {
                        uninstall_trust_store()
                            .map(|()| i18n::t(&locale, "certOutcome.uninstalled"))
                    },
                );
            }
        }
        MenuAction::RotateCert => {
            if confirm_rotate_cert(locale) {
                let locale = locale.to_string();
                spawn_cert_action(
                    "rotate",
                    dialog_title(&i18n::t(&locale, "menu.rotateCert")),
                    locale.clone(),
                    trust,
                    move || {
                        rotate_certificate().map(|report| {
                            i18n::t_args(
                                &locale,
                                "certOutcome.rotateSuccessTemplate",
                                &[(
                                    "outcome",
                                    &trust_store_outcome_text(report.install_outcome, &locale),
                                )],
                            )
                        })
                    },
                );
            }
        }
        MenuAction::RemoveAllLocalState => {
            if confirm_remove_all_local_state(locale) {
                spawn_remove_all_and_quit(app_data.to_path_buf(), locale.to_string());
            }
        }
        // T-185 + T-193: pause = write `stop.flag` only. `dnsqb-service` polls
        // it (`pause_watch`) and serves every query through the unfiltered
        // baseline while it exists — the service stays up, the watchdog keeps
        // supervising it. Resume = remove the flag; `ensure_sibling_running` is
        // an idempotent no-op unless both the service and watcher died during
        // the pause. The label the user clicked tells us which.
        MenuAction::TogglePause => {
            if stop_flag_is_set(app_data) {
                clear_stop_flag(app_data);
                ensure_sibling_running(app_data, InstanceRole::Service);
                tracing::info!("filtering resumed by the user");
            } else if confirm_pause(locale) {
                if let Err(err) = set_stop_flag(app_data) {
                    tracing::warn!("could not write stop.flag: {err}");
                }
            }
        }
        // T-185: bring the watchdog back if it stopped (idempotent — a no-op
        // when a watcher is already running). This is the only actionable
        // recovery for a dead watcher; there is no automatic one yet.
        MenuAction::RestoreSupervision => {
            ensure_sibling_running(app_data, InstanceRole::Watcher);
        }
        // T-185: quit the whole app. Write both flags and exit the tray; the
        // watcher picks up `quit.flag` on its next tick, stops the service and
        // exits itself. `stop.flag` covers the gap so nothing is respawned in
        // between.
        MenuAction::QuitApp => {
            if confirm_quit(locale) {
                if let Err(err) = set_stop_flag(app_data) {
                    tracing::warn!("could not write stop.flag: {err}");
                }
                if let Err(err) = set_quit_flag(app_data) {
                    tracing::warn!("could not write quit.flag: {err}");
                }
                *control_flow = ControlFlow::Exit;
            }
        }
        // "Сховати іконку" only exits this process — dnsqb-service and the
        // watcher keep running, filtering stays on. "Вийти з DNS Quorum
        // Filter" above is the one that stops everything.
        MenuAction::HideIcon => *control_flow = ControlFlow::Exit,
        MenuAction::Unknown => {}
    }
}

/// Runs one admin-channel action (`reset`/`shutdown`) on its own throwaway
/// OS thread with its own tiny runtime — these are rare, user-initiated
/// clicks, not a hot path, so building a fresh [`AdminClient`] per call is
/// fine here (same cadence the old `dnsqb-ui` Tauri commands already used) —
/// unlike [`status::spawn`]'s ~30x/minute poll, which specifically must not
/// rebuild one every tick.
fn spawn_admin_action<F, Fut>(app_data: PathBuf, port: u16, action_name: &'static str, action: F)
where
    F: FnOnce(AdminClient) -> Fut + Send + 'static,
    Fut: std::future::Future<Output = Result<(), AdminClientError>>,
{
    std::thread::spawn(move || {
        let Ok(runtime) = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
        else {
            tracing::error!("failed to start a runtime for the {action_name} action");
            return;
        };
        runtime.block_on(async move {
            match AdminClient::new(&app_data, port) {
                Ok(client) => match action(client).await {
                    Ok(()) => tracing::info!("{action_name} succeeded"),
                    Err(err) => tracing::warn!("{action_name} failed: {err}"),
                },
                Err(err) => {
                    tracing::warn!("{action_name} failed to build an admin client: {err}");
                }
            }
        });
    });
}

/// Every native dialog's title, so a user with several DNS-QF popups open
/// (or a screenshot shared for support) can always see which app and which
/// build it came from at a glance (user request, 2026-09-22 v0.5.0 smoke
/// test) - one shared function so the format can't drift between call
/// sites the way the ten literal titles it replaced already had (`"dns-
/// quorum-filter"` lowercase-hyphenated on the About dialog vs `"DNS Quorum
/// Filter"` everywhere else).
fn dialog_title(action: &str) -> String {
    format!("DNS Quorum Filter {} — {action}", env!("CARGO_PKG_VERSION"))
}

/// Found in live smoke-testing (2026-09-22): the install/rotate success
/// dialogs used to forward `TrustStoreOutcome`'s raw `{:?}` ("Installed" /
/// "`AlreadyInstalled`") straight into a Ukrainian "Успішно: {outcome}"
/// sentence, mixing languages mid-sentence. `TrustStoreOutcome`/
/// `RotationReport`'s own `Debug`/`Display` are deliberately English (their
/// own doc comments: for logs) - this is the translation step that was
/// supposed to happen at the tray boundary but didn't. **T-151 Батч 5.5:**
/// generalized from a hardcoded Ukrainian match into a `t()` lookup, same
/// reasoning, any locale.
fn trust_store_outcome_text(outcome: TrustStoreOutcome, locale: &str) -> String {
    match outcome {
        TrustStoreOutcome::Installed => i18n::t(locale, "certOutcome.installed"),
        TrustStoreOutcome::AlreadyInstalled => i18n::t(locale, "certOutcome.alreadyInstalled"),
    }
}

/// Runs one trust-store action (`install`/`uninstall`) on its own throwaway
/// OS thread — unlike [`spawn_admin_action`], this is a synchronous local
/// `certutil` call, not an admin-HTTP-channel round trip, so no `tokio`
/// runtime is needed at all. Reports the outcome **both** ways: logged (as
/// every other action here does) and via a native dialog on this same
/// thread — this crate builds with `windows_subsystem = "windows"` (no
/// console), so a log line alone is invisible to a user who clicked a menu
/// item and is watching for a result. A silent failure here would leave the
/// user believing a trust-store change succeeded when it didn't — exactly
/// the "no on-screen indication" failure class this crate's own module doc
/// comment already names for "Зупинити фільтрацію" (advisor-caught before
/// commit, not written this way from the start).
fn spawn_trust_store_action<F, E>(
    action_name: &'static str,
    dialog_title: String,
    locale: String,
    action: F,
) where
    F: FnOnce() -> Result<String, E> + Send + 'static,
    E: std::fmt::Display,
{
    std::thread::spawn(move || match action() {
        Ok(outcome) => {
            tracing::info!("{action_name} succeeded: {outcome}");
            rfd::MessageDialog::new()
                .set_title(dialog_title)
                .set_description(i18n::t_args(
                    &locale,
                    "dialog.successTemplate",
                    &[("outcome", &outcome)],
                ))
                .set_level(rfd::MessageLevel::Info)
                .set_buttons(rfd::MessageButtons::Ok)
                .show();
        }
        Err(err) => {
            let err = err.to_string();
            tracing::warn!("{action_name} failed: {err}");
            rfd::MessageDialog::new()
                .set_title(dialog_title)
                .set_description(i18n::t_args(
                    &locale,
                    "dialog.failedTemplate",
                    &[("err", &err)],
                ))
                .set_level(rfd::MessageLevel::Error)
                .set_buttons(rfd::MessageButtons::Ok)
                .show();
        }
    });
}

/// [`spawn_trust_store_action`] plus a trust re-poll after the action returns
/// (T-191) — every cert menu item changes `CurrentUser\Root`, so the status
/// icon's colour needs to catch up. `request_recheck` fires *after* the
/// `certutil` call, not at click time: firing at click would race the
/// ~100–300 ms action and re-poll before the store actually changed.
fn spawn_cert_action<F, E>(
    action_name: &'static str,
    dialog_title: String,
    locale: String,
    trust: &TrustState,
    action: F,
) where
    F: FnOnce() -> Result<String, E> + Send + 'static,
    E: std::fmt::Display,
{
    let trust = trust.clone();
    spawn_trust_store_action(action_name, dialog_title, locale, move || {
        let outcome = action();
        trust.request_recheck();
        outcome
    });
}

/// Set by [`spawn_remove_all_and_quit`] once the report dialog is dismissed
/// and the app-data wipe helper is spawned — the event loop exits on its next
/// tick (a worker thread has no handle to `control_flow`).
static QUIT_REQUESTED: AtomicBool = AtomicBool::new(false);

/// T-195 — "Повністю видалити": clear the out-of-tree state, show the report,
/// then bring the whole app down and hand off the rest to the OS.
///
/// Not [`spawn_cert_action`]: the shutdown has to happen *after* the report
/// dialog, and `spawn_cert_action` shows its dialog after the closure returns.
/// Order: [`remove_all_local_state`] (cert + Credential Manager secrets, none
/// of them files in app-data) → report dialog → `stop.flag` + `quit.flag`
/// (the watcher stops `dnsqb-service` and exits on its next tick, exactly like
/// [`QUIT_APP_ID`]) → spawn the detached wipe helper (it waits for every
/// DNS-QF process to exit before deleting) → open Windows Settings →
/// `QUIT_REQUESTED` so this tray exits too.
fn spawn_remove_all_and_quit(app_data: PathBuf, locale: String) {
    std::thread::spawn(move || {
        let report = format_uninstall_report(&remove_all_local_state(Some(&app_data)), &locale);
        tracing::info!("remove-all-local-state finished:\n{report}");
        rfd::MessageDialog::new()
            .set_title(dialog_title(&i18n::t(&locale, "menu.removeAll")))
            .set_description(i18n::t_args(
                &locale,
                "uninstall.reportDialogTemplate",
                &[("report", &report)],
            ))
            .set_level(rfd::MessageLevel::Info)
            .set_buttons(rfd::MessageButtons::Ok)
            .show();
        if let Err(err) = set_stop_flag(&app_data) {
            tracing::warn!("could not write stop.flag: {err}");
        }
        if let Err(err) = set_quit_flag(&app_data) {
            tracing::warn!("could not write quit.flag: {err}");
        }
        self_uninstall::spawn_app_data_dir_wipe(&app_data);
        browser::open_windows_apps_settings();
        QUIT_REQUESTED.store(true, Ordering::SeqCst);
    });
}

/// One-shot first-run onboarding offer (T-188). Fires at most once per
/// process (`offered` latch), and only once the trust-watch thread has a
/// *confirmed* `certutil` reading — on a fresh MSIX install `cert.pem` does
/// not exist when the tray starts (T-187), so an earlier check would read the
/// optimistic seed, not the store. [`onboarding::should_offer_onboarding`] is
/// the pure predicate.
fn maybe_offer_onboarding(
    offered: &mut bool,
    app_data: &Path,
    port: u16,
    trust: &TrustState,
    trusted: bool,
    locale: &str,
) {
    if *offered {
        return;
    }
    let seen = onboarding::onboarding_seen(app_data);
    if onboarding::should_offer_onboarding(trust.is_confirmed(), trusted, seen) {
        *offered = true;
        run_setup_wizard(app_data, port, trust, locale);
    }
}

/// T-229: offers the nudge popup if due, then closes it (click or expiry).
/// One call site keeps this batch of tightly-coupled state out of `main`'s
/// own body — the same reason `refresh_tray`/`maybe_offer_onboarding` are
/// already their own functions.
fn drive_browser_nudge(
    offered: &mut bool,
    app_data: &Path,
    observed: TrayStatus,
    target: &tao::event_loop::EventLoopWindowTarget<()>,
    tray_icon: &TrayIcon,
    event: &tao::event::Event<()>,
    popup: &mut Option<nudge_popup::NudgePopup>,
) {
    maybe_offer_browser_nudge(offered, app_data, observed, target, tray_icon, popup);
    if popup
        .as_ref()
        .is_some_and(|p| p.should_close(event, nudge_popup::POPUP_LIFETIME))
    {
        *popup = None;
    }
}

/// One-shot "point your browser at this" nudge (T-229). Fires at most once
/// **per process** (`offered` latch) regardless of whether rendering
/// actually succeeds — a failed render (e.g. no monitor detected) is not
/// worth retrying every tick. The persisted `browser-nudge.seen` marker is
/// only written once [`nudge_popup::spawn`] actually returns a window — that
/// marker means "shown", not "decided to show", so a rendering failure can't
/// silently burn the one-shot latch a future launch could still use.
/// [`browser_nudge::should_offer_browser_nudge`] is the pure predicate.
fn maybe_offer_browser_nudge(
    offered: &mut bool,
    app_data: &Path,
    observed: TrayStatus,
    target: &tao::event_loop::EventLoopWindowTarget<()>,
    tray_icon: &TrayIcon,
    popup: &mut Option<nudge_popup::NudgePopup>,
) {
    if *offered {
        return;
    }
    let total_queries = match observed {
        TrayStatus::Filtering { total, .. } => Some(total),
        _ => None,
    };
    let seen = browser_nudge::browser_nudge_seen(app_data);
    let first_seen = browser_nudge::first_seen(app_data);
    if browser_nudge::should_offer_browser_nudge(SystemTime::now(), first_seen, total_queries, seen)
    {
        *offered = true;
        if let Some(window) = nudge_popup::spawn(target, tray_icon.rect()) {
            *popup = Some(window);
            browser_nudge::mark_browser_nudge_seen(app_data);
        } else {
            tracing::warn!("browser nudge popup failed to render");
        }
    }
}

/// Set while a [`run_setup_wizard`] welcome dialog is open, so the auto-offer
/// and the "Майстер налаштування" menu item can't stack two modal dialogs
/// (each able to spawn its own `ensure_installed`).
static WIZARD_ACTIVE: AtomicBool = AtomicBool::new(false);

/// The first-run wizard (T-188): a welcome dialog offering to install the
/// local certificate, then — on «Так» and a successful install — open the
/// browser-setup page. Runs entirely on a throwaway thread because `rfd`
/// dialogs block and both callers (the auto-offer above and the "Майстер
/// налаштування" menu item) are on the event-loop thread. Reuses
/// [`spawn_cert_action`] for the install half, so the trust icon re-polls
/// afterward for free. `onboarding.seen` is written on «Пізніше» and on a
/// *successful* install, never on a failed one (that should re-offer next
/// launch); the menu item is the manual re-entry regardless.
fn run_setup_wizard(app_data: &Path, port: u16, trust: &TrustState, locale: &str) {
    if WIZARD_ACTIVE.swap(true, Ordering::SeqCst) {
        return; // a welcome dialog is already open
    }
    let app_data = app_data.to_path_buf();
    let trust = trust.clone();
    let locale = locale.to_string();
    std::thread::spawn(move || {
        let proceed = confirm(
            &i18n::t(&locale, "onboarding.title"),
            &i18n::t(&locale, "onboarding.description"),
            rfd::MessageLevel::Info,
        );
        WIZARD_ACTIVE.store(false, Ordering::SeqCst);
        if !proceed {
            onboarding::mark_onboarding_seen(&app_data);
            return;
        }
        let cert_path = app_data.join("cert.pem");
        let url = format!("https://127.0.0.1:{port}/admin/ui");
        spawn_cert_action(
            "onboarding-install",
            dialog_title(&i18n::t(&locale, "menu.installCert")),
            locale.clone(),
            &trust,
            move || -> Result<String, dnsqb_service::TrustStoreError> {
                let outcome = ensure_installed(&cert_path)?;
                // Reached only on a successful install — a failure bails on the
                // `?` above with the marker still unwritten.
                onboarding::mark_onboarding_seen(&app_data);
                browser::open_in_default_browser(&url);
                Ok(trust_store_outcome_text(outcome, &locale))
            },
        );
    });
}

/// The one shape every "are you sure?" dialog below shares: [`dialog_title`]
/// for the header, always Yes/No buttons, always "did they pick Yes" as the
/// answer. Only the description text and severity actually differ per
/// dialog, so those stay ordinary arguments at each named `confirm_*`
/// call site below — this collapses the six-line `MessageDialog` builder
/// that used to be copy-pasted at every one of those sites (user question,
/// 2026-09-22: "чи можна винести це в одне місце" — this is that place),
/// without losing the named function + doc comment that explains *why*
/// that particular dialog exists, which a single generic call from the
/// menu-dispatch match arm would have.
fn confirm(action: &str, description: &str, level: rfd::MessageLevel) -> bool {
    rfd::MessageDialog::new()
        .set_title(dialog_title(action))
        .set_description(description)
        .set_level(level)
        .set_buttons(rfd::MessageButtons::YesNo)
        .show()
        == rfd::MessageDialogResult::Yes
}

/// Native confirm dialog before `certutil -addstore` — this pops the OS's
/// own confirmation dialog too (a second, separate prompt) unless/until
/// T-49's open "is certutil silent?" question is settled by a real run; see
/// `trust_store.rs`'s module doc comment.
fn confirm_install_cert(locale: &str) -> bool {
    confirm(
        &i18n::t(locale, "menu.installCert"),
        &i18n::t(locale, "confirm.installCert.description"),
        rfd::MessageLevel::Info,
    )
}

/// Native confirm dialog before `certutil -delstore` — names the real
/// consequence (browser warning returns), same pattern as [`confirm_pause`].
fn confirm_uninstall_cert(locale: &str) -> bool {
    confirm(
        &i18n::t(locale, "menu.uninstallCert"),
        &i18n::t(locale, "confirm.uninstallCert.description"),
        rfd::MessageLevel::Warning,
    )
}

/// Native confirm dialog before certificate rotation — names every consequence
/// *before* the user acts: the old `CurrentUser\Root` entries are removed, a
/// fresh key is generated and the new certificate installed in their place, and
/// the running `dnsqb-service` keeps serving the *previous* certificate (it
/// holds its TLS config from startup) until it is restarted. In that window the
/// browser shows an untrusted-certificate warning on `/admin/ui` because the
/// certificate on the wire is no longer in the trust store; restarting
/// `dnsqb-service` clears it. (The tray's own status poll is unaffected —
/// [`status::spawn`] keeps its cached client, still pinned to and matching the
/// still-served previous certificate.)
fn confirm_rotate_cert(locale: &str) -> bool {
    confirm(
        &i18n::t(locale, "menu.rotateCert"),
        &i18n::t(locale, "confirm.rotateCert.description"),
        rfd::MessageLevel::Warning,
    )
}

/// Native confirm dialog before T-70/T-195's full removal — names everything
/// it clears (the trusted certificate, the three Credential Manager secrets,
/// **and** the whole app-data directory) and what happens next: the app
/// closes and Windows Settings opens for the final "Remove" click (MSIX,
/// T-156, gives the app no uninstall-time hook of its own).
fn confirm_remove_all_local_state(locale: &str) -> bool {
    confirm(
        &i18n::t(locale, "menu.removeAll"),
        &i18n::t(locale, "confirm.removeAll.description"),
        rfd::MessageLevel::Warning,
    )
}

/// One line per artifact, never a single collapsed pass/fail — the same
/// discipline [`UninstallReport`] itself follows.
fn format_uninstall_report(report: &UninstallReport, locale: &str) -> String {
    fn line(label: &str, outcome: ArtifactOutcome, locale: &str) -> String {
        let key = match outcome {
            ArtifactOutcome::Removed => "uninstall.outcome.removed",
            ArtifactOutcome::NotPresent => "uninstall.outcome.notPresent",
            ArtifactOutcome::Failed(_) => "uninstall.outcome.failed",
        };
        format!("{label}: {}", i18n::t(locale, key))
    }
    [
        line(
            &i18n::t(locale, "uninstall.label.cert"),
            report.cert,
            locale,
        ),
        line(
            &i18n::t(locale, "uninstall.label.tlsKey"),
            report.tls_key,
            locale,
        ),
        line(
            &i18n::t(locale, "uninstall.label.persistenceKey"),
            report.persistence_key,
            locale,
        ),
        line(
            &i18n::t(locale, "uninstall.label.maxmindCreds"),
            report.maxmind_creds,
            locale,
        ),
        line(
            &i18n::t(locale, "uninstall.label.personalZoneKey"),
            report.personal_zone_key,
            locale,
        ),
    ]
    .join("\n")
}

/// Found in live smoke-testing (2026-09-22): the settings-page URL here was a
/// literal `https://127.0.0.1/admin/ui` with no port at all — following it
/// hits the browser's default port 443, not this instance's actual (possibly
/// non-default) `DoH` port. `port` was simply never plumbed into this function;
/// `MenuAction::OpenSettings` right above already has the correct pattern.
/// Pulled out as its own pure function so the fix has a regression test —
/// `show_about_dialog` itself calls a real blocking `rfd` dialog and can't be
/// unit tested directly.
fn about_dialog_text(port: u16, locale: &str) -> String {
    i18n::t_args(
        locale,
        "about.bodyTemplate",
        &[
            ("version", env!("CARGO_PKG_VERSION")),
            ("port", &port.to_string()),
        ],
    )
}

fn show_about_dialog(port: u16, locale: &str) {
    rfd::MessageDialog::new()
        .set_title(dialog_title(&i18n::t(locale, "menu.about")))
        .set_description(about_dialog_text(port, locale))
        .set_level(rfd::MessageLevel::Info)
        .set_buttons(rfd::MessageButtons::Ok)
        .show();
}

/// Native confirm dialog before pausing filtering (T-185 / T-193). Names the
/// consequence precisely: DNS keeps working (the service stays up, T-193), but
/// quorum + `GeoIP` stop applying — the user's own lists still do. Reversible
/// from the same menu, and a fresh app launch also clears `stop.flag`, so the
/// dialog says so. Deliberately does **not** claim "everything goes unfiltered"
/// — a blocklisted domain is still blocked during a pause.
fn confirm_pause(locale: &str) -> bool {
    confirm(
        &i18n::t(locale, "menu.pause"),
        &i18n::t(locale, "confirm.pause.description"),
        rfd::MessageLevel::Warning,
    )
}

/// Native confirm dialog before quitting the whole app (T-185) — this stops
/// the service, the watchdog and the tray. Same blast-radius warning shape as
/// [`confirm_pause`], stronger wording.
fn confirm_quit(locale: &str) -> bool {
    confirm(
        &i18n::t(locale, "confirm.quit.title"),
        &i18n::t(locale, "confirm.quit.description"),
        rfd::MessageLevel::Warning,
    )
}

#[cfg(test)]
mod tests {
    use super::{
        about_dialog_text, format_uninstall_report, menu_action_for, trust_store_outcome_text,
        MenuAction,
    };
    use dnsqb_service::{ArtifactOutcome, TrustStoreOutcome, UninstallReport};

    // Found in live smoke-testing (2026-09-22): the About dialog's settings
    // URL used to be a literal with no port, hitting 443 instead of the
    // actual (possibly non-default) DoH port on click.
    #[test]
    fn about_dialog_text_includes_the_actual_port() {
        let text = about_dialog_text(8443, "uk");
        assert!(
            text.contains("https://127.0.0.1:8443/admin/ui"),
            "must carry the real port, not a bare https://127.0.0.1/admin/ui: {text:?}"
        );
        let custom = about_dialog_text(9999, "uk");
        assert!(
            custom.contains(":9999/"),
            "must reflect a non-default port too: {custom:?}"
        );
    }

    // Found in live smoke-testing (2026-09-22): the install/rotate success
    // dialogs used to forward TrustStoreOutcome's raw `{:?}` straight into the
    // Ukrainian "Успішно: {outcome}" sentence, mixing languages mid-sentence
    // ("Успішно: Installed"). Guard both variants stay real Ukrainian text,
    // never the English Debug label. T-151 Батч 5.5: generalized to `t()` -
    // pin "uk" explicitly so the assertion doesn't depend on the OS locale of
    // whatever machine runs this test (i18n.rs's own module doc comment).
    #[test]
    fn trust_store_outcome_text_never_leaks_the_raw_debug_label() {
        for outcome in [
            TrustStoreOutcome::Installed,
            TrustStoreOutcome::AlreadyInstalled,
        ] {
            let text = trust_store_outcome_text(outcome, "uk");
            assert!(
                !text.contains("Installed"),
                "must not leak the raw Debug identifier: {text:?}"
            );
            assert!(
                text.chars()
                    .any(|c| matches!(c, 'а'..='я' | 'і' | 'ї' | 'є' | 'ґ')),
                "must actually be Ukrainian text: {text:?}"
            );
        }
    }

    // Keyed on the literal id strings `build_menu` passes to
    // `MenuItem::with_id`, NOT the `*_ID` constants — so a constant silently
    // changing value is caught here even though a constant-keyed table would
    // still pass (it would reference the same changed constant on both sides).
    #[test]
    fn menu_action_for_maps_each_built_menu_id_to_its_action() {
        let cases = [
            ("open-settings", MenuAction::OpenSettings),
            ("restart", MenuAction::ResetCacheAndLog),
            ("about", MenuAction::ShowAbout),
            ("setup-wizard", MenuAction::RunSetupWizard),
            ("install-cert", MenuAction::InstallCert),
            ("uninstall-cert", MenuAction::UninstallCert),
            ("rotate-cert", MenuAction::RotateCert),
            ("remove-all-local-state", MenuAction::RemoveAllLocalState),
            ("pause-resume-filtering", MenuAction::TogglePause),
            ("restore-supervision", MenuAction::RestoreSupervision),
            ("quit-app", MenuAction::QuitApp),
            ("close", MenuAction::HideIcon),
        ];
        for (id, expected) in cases {
            assert_eq!(menu_action_for(id), expected, "id {id:?}");
        }
    }

    #[test]
    fn menu_action_for_unrecognised_ids_are_unknown() {
        for id in ["", "not-a-real-id", "open-setting", "OPEN-SETTINGS", "quit"] {
            assert_eq!(menu_action_for(id), MenuAction::Unknown, "id {id:?}");
        }
    }

    fn report_of(outcome: ArtifactOutcome) -> UninstallReport {
        UninstallReport {
            cert: outcome,
            tls_key: outcome,
            persistence_key: outcome,
            maxmind_creds: outcome,
            personal_zone_key: outcome,
        }
    }

    #[test]
    fn uninstall_report_has_one_labelled_line_per_artifact() {
        let text = format_uninstall_report(&report_of(ArtifactOutcome::Removed), "uk");
        assert_eq!(text.lines().count(), 5);
        for label in [
            "Сертифікат",
            "TLS-ключ",
            "Ключ шифрування",
            "Креденшели MaxMind",
            "Ключ особистої зони",
        ] {
            assert!(text.contains(label), "missing label {label}");
        }
    }

    #[test]
    fn uninstall_report_maps_each_outcome_to_its_phrase() {
        assert!(
            format_uninstall_report(&report_of(ArtifactOutcome::Removed), "uk")
                .lines()
                .all(|line| line.ends_with(": видалено"))
        );
        assert!(
            format_uninstall_report(&report_of(ArtifactOutcome::NotPresent), "uk")
                .lines()
                .all(|line| line.ends_with(": не було встановлено"))
        );
        assert!(
            format_uninstall_report(&report_of(ArtifactOutcome::Failed("x")), "uk")
                .lines()
                .all(|line| line.ends_with(": НЕ ВДАЛОСЯ видалити"))
        );
    }

    #[test]
    fn uninstall_report_renders_each_field_independently() {
        let text = format_uninstall_report(
            &UninstallReport {
                cert: ArtifactOutcome::Removed,
                tls_key: ArtifactOutcome::NotPresent,
                persistence_key: ArtifactOutcome::Failed("secret store error"),
                maxmind_creds: ArtifactOutcome::Removed,
                personal_zone_key: ArtifactOutcome::NotPresent,
            },
            "uk",
        );
        let lines: Vec<&str> = text.lines().collect();
        assert_eq!(
            lines,
            vec![
                "Сертифікат: видалено",
                "TLS-ключ: не було встановлено",
                "Ключ шифрування: НЕ ВДАЛОСЯ видалити",
                "Креденшели MaxMind: видалено",
                "Ключ особистої зони: не було встановлено",
            ]
        );
    }

    // T-151 Батч 5.5: the same report in English, proving the labels/outcome
    // phrases actually come from the dictionary, not leftover Ukrainian
    // literals still hardcoded somewhere in `format_uninstall_report`.
    #[test]
    fn uninstall_report_translates_into_english() {
        let text = format_uninstall_report(&report_of(ArtifactOutcome::Removed), "en");
        assert_eq!(
            text.lines().collect::<Vec<_>>(),
            vec![
                "Certificate: removed",
                "TLS key: removed",
                "Encryption key: removed",
                "MaxMind credentials: removed",
                "Personal-zone key: removed",
            ]
        );
    }
}
